# -*- coding: utf-8 -*-
"""GenerateClozePrompts_01Juin2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCAgE_aPIuK0HeMnb1IELQNpvbeTq5pq
"""

# Le programme de génération des invites de type cloze (avec un mot manquant)
# Dernière modification: 13 Janvier 2025

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

#spaceHolderGroupes_path = '/content/drive/MyDrive/SpaceHolderGroupes/'
connectors_path =         '/content/drive/MyDrive/Connectors/'
generatedPrompts_path =   '/content/drive/MyDrive/GeneratedPrompts/'
spaceHolderGroupes_path = '/content/drive/MyDrive/ToDo/'

#filtredPrompts_path = '/content/drive/MyDrive/filtredPrompts/'

from pathlib import os
import pandas as pd
#import numpy as np
#from matplotlib import pyplot as plt
from pathlib import Path

# Définition d'une fonction qui génère des invites conformément au modèle d'invites désiré
# et puis les enregistrent dans un fichier au format -.csv / -.xlsx

def generatedPrompts(spaceHolderFileName, connectorFileName):

   # lecture des fichiers (des espaces réservés dans : 'spaceHolderGroupes_path' et des connecteurs : 'connectors_path') -.csv
   dfSpaceHolderGroupes = pd.read_csv(spaceHolderFileName,sep=";", skipinitialspace=True)
   # filtrer le fichier des espaces réservés lu selon la rubrique -ignore == non
   dfSpaceHolderGroupes = dfSpaceHolderGroupes.loc[dfSpaceHolderGroupes['ignore'] == 'non']
   dfConnectors = pd.read_csv(connectorFileName,sep=";", skipinitialspace=True)

   # séparer les connecteurs par catégorie gramaticale : - Singulier / - Pluriel

   dfConnectorsP = dfConnectors[['connector','reference','plural']]
   dfConnectorsP = dfConnectorsP.rename(columns={"plural": "connectorVerb"})
   dfConnectorsS = dfConnectors[['connector','reference','singular']]
   dfConnectorsS = dfConnectorsS.rename(columns={"singular": "connectorVerb"})

   #print(dfConnectorsP)
   #print(dfConnectorsS)
   # séparer les espaces réservés par catégorie gramaticale : - Singulier / - Pluriel

   dfSpaceHolderP = dfSpaceHolderGroupes.loc[dfSpaceHolderGroupes['cat_gr'] == 'P']
   dfSpaceHolderS = dfSpaceHolderGroupes.loc[dfSpaceHolderGroupes['cat_gr'] == 'S']

   #print(dfSpaceHolderP)
   #print(dfSpaceHolderS)

   # génération des prompts en faisant la jointure : - Produit cartésien des espaces réservés et les connecteurs

   generatedPromptsP = dfSpaceHolderP.merge(dfConnectorsP, how='cross')
   generatedPromptsS = dfSpaceHolderS.merge(dfConnectorsS, how='cross')

   #print(generatedPromptsP)
   #print(generatedPromptsS)

   # concatenation des prompts (- Singulier / - Pluriel)
   generatedPrompts = pd.concat([generatedPromptsP, generatedPromptsS])
   generatedPrompts['prompts'] = generatedPrompts['spaceHolder'] + " " + generatedPrompts['connectorVerb'] + " [MASK]."

   print(generatedPrompts)

   return generatedPrompts

# Parcourir la liste des fichiers -.csv (les mentions de handicap et les verbes connceteurs)
file_paths_spaceHolder = list(Path(spaceHolderGroupes_path).glob("*.csv"))
file_path_connectors = list(Path(connectors_path).glob("*.csv"))
dfResults = []

for file_connector in file_path_connectors:
    # extraire le nom du fichier sans l'extention
    connectorFileName,ext = file_connector.name.split(sep=".")

    for file_spaceHolder in file_paths_spaceHolder:
        # extraire le nom du fichier sans l'extention
        spaceHolderFileName,ext = file_spaceHolder.name.split(sep=".")

        # génerer les prompts avec le fichier des mentions de handicap et celui des verbes connecteurs
        dfResults = generatedPrompts(file_spaceHolder, file_connector)

        # le nom du fichier des prompts résultant: -.csv ou -.excel)
        outputFileNameCsv = "prompts_" + spaceHolderFileName +  "_" + connectorFileName + ".csv"
        #outputFileNameExcel = "prompts_" + spaceHolderFileName +  "_" + connectorFileName + ".xlsx"

        # transfert des résultats dans un fichier - csv et - excel.
        dfResults.to_csv(generatedPrompts_path + outputFileNameCsv, sep=";", index=False)
        #dfResults.to_excel(generatedPrompts_path + outputFileNameExcel, index=False)

        #print(outputFileNameCsv)
        #print(outputFileNameExcel)

# Définition d'une fonction qui filtre les invites créées selon la rubrique -Ignore
# et puis les enregistrent dans un fichier au format -.csv / -.xlsx

#def filterPrompts(fileName):

   #dfPrompts = pd.read_csv(fileName,sep=";", skipinitialspace=True)
   #dfFiltredPrompts = dfPrompts.loc[dfPrompts['ignore'] == 'non']

   #return dfFiltredPrompts

# Parcourir la liste des fichiers -.csv qui contiennent les invites à filtrer
#file_paths_toFilter = list(Path(generatedPrompts_path).glob("*.csv"))
#dfFilters = []

#for file_toFilter in file_paths_toFilter:
    # extraire le nom du fichier sans l'extention
    #filterFileName,ext = file_toFilter.name.split(sep=".")

    # filtrer les prompts selon la rubrique -Ignore == non
    #dfFilters = filterPrompts(file_toFilter)

    # le nom du fichier des prompts résultant: -.csv ou -.excel)
    #outputFileNameCsv = "filtred_" + filterFileName  + ".csv"
    #outputFileNameExcel = "filtred_" + filterFileName + ".xlsx"

    # transfert des résultats dans un fichier - csv et - excel.
    #dfFilters.to_csv(filtredPrompts_path + outputFileNameCsv, sep=";", index=False)
    #dfFilters.to_excel(filtredPrompts_path + outputFileNameExcel, index=False)

    #print(outputFileNameCsv)
    #print(outputFileNameExcel)