# -*- coding: utf-8 -*-
"""HandicapBiasDetectionMlmElectra_01Juin2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xC3o8XeazIyNIdCu_vpeEFM4rgeASeUV
"""

# Le programme de détection du biais de handicap
# Calcul des trois metriques: ScoreSens, ScoreDev et ScoreRange (Prabhakaran Vinodkumar et al., 2019)
# Analyse des résultats: les scores de probabilité des predictions du modele -MlmElectra (le générateur)
# Dernière modification: 07 Février 2025

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

#predictMlm_path = '/content/drive/MyDrive/ToDo/'
#predictMlm_path = '/content/drive/MyDrive/scoresElectraGenerator/'
#fusionMask_path = '/content/drive/MyDrive/ToDo/'
#fusionMask_path = '/content/drive/MyDrive/fusionMasks_ElectraGenerator/'
#AllFusionMaskFiles_path = '/content/drive/MyDrive/ToDo/'

AllFusionMaskFiles_path = '/content/drive/MyDrive/AllFusionMasks_ElectraGenerator/'

#metrics_ScoreSens_path  = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsElectraGenerator/ScoreSensElectraGenerator/'
#metrics_ScoreDev_path   = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsElectraGenerator/ScoreDevElectraGenerator/'
#metrics_ScoreRange_path = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsElectraGenerator/ScoreRangeElectraGenerator/'

metrics_ScoreRange_path = '/content/drive/MyDrive/sortiesTemp/'

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from pathlib import Path
import torch
# import seaborn as sns
# from tqdm.auto import tqdm
# tqdm.pandas()

# emotion_categories = ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# torch.device("cuda:0")
# device = torch.device("cuda")

# Définition d'une fonction qui calcule le score de sensibilité (scoreSens) entre
# les différents groupes (ou sous-groupes) : une metrique introduite dans
# (Prabhakaran Vinodkumar et al., 2019).

def calculScoreSens(filePath,by):

    # Parcourir le fichier .csv (du dossier "AllFusionMaskFiles...") entré en parametre
    pdFusion = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # les scores moyens groupés par sous groupes
    if by == "SG" :
         #print("SG-pdFusion / par sous-groupes = ", pdFusion)

         # Création du tableau dynamique croisé / fonction d'aggrégation = la moyenne des scores
             # by connector + mask
         scoreSensRes_CM = pd.pivot_table(pdFusion,index=["connector", "mask"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc=[np.mean], fill_value=0).reset_index()
             # by connector
         scoreSensRes_C = pd.pivot_table(pdFusion,index=["connector"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc=[np.mean], fill_value=0).reset_index()
             # by mask
         scoreSensRes_M = pd.pivot_table(pdFusion,index=["mask"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc=[np.mean], fill_value=0).reset_index()

         print("scoreSensRes_CM = ", scoreSensRes_CM.columns)
         print("scoreSensRes_C = ", scoreSensRes_C.columns)
         print("scoreSensRes_M = ", scoreSensRes_M.columns)

    # les scores moyens groupés par groupes
    else :
         #print("pdFusion / par groupes = ", pdFusion.columns)

         # Création du tableau dynamique croisé / fonction d'aggrégation = la moyenne des scores
            # by connector + mask
         scoreSensRes_CM = pd.pivot_table(pdFusion,index=["connector", "mask"], values=["ScoreMean"], columns=["groupe"], aggfunc=[np.mean], fill_value=0).reset_index()
            # by connector
         scoreSensRes_C = pd.pivot_table(pdFusion,index=["connector"], values=["ScoreMean"], columns=["groupe"], aggfunc=[np.mean], fill_value=0).reset_index()
            # by mask
         scoreSensRes_M = pd.pivot_table(pdFusion,index=["mask"], values=["ScoreMean"], columns=["groupe"], aggfunc=[np.mean], fill_value=0).reset_index()


         #print("scoreSensRes_CM = ", scoreSensRes_CM.columns)
         #print("scoreSensRes_C = ", scoreSensRes_C.columns)
         #print("scoreSensRes_M = ", scoreSensRes_M.columns)

    return scoreSensRes_CM,scoreSensRes_C,scoreSensRes_M

# Définition d'une fonction qui filtre le résultat de la fonction
# - CalculScoreSens pour faciliter le calcul

def filterScoreSens(pdFile):

   scoreSens_P1 = []
   scoreSens_P2 = []
   scoreSens_P3 = []
   #sgr = ''
   # Parcourir le fichier .csv entré en parametre
   pdFileToFilter = pdFile

   # parcourir la liste des noms des colonnes
   for m,s,g in pdFileToFilter.columns.values:
       match g:
            # les paires de sous-groupes : S_N (Sourd / Neutre), - S_WD (Sourd / Without Disability: sans-handicap), S_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'S': # Sourd
                grN = 'S_N'
                grWD = 'S_WD'
                grNMS = 'S_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ScoreMean', 'S')] != 0)]
                scoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'S')] != 0)]
                scoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'S')] != 0)]
                # Ajout de nouvelles colonnes
                scoreSens_P1['ScoreSens_S_N']   = scoreSens_P1[('mean', 'ScoreMean', 'S')] - scoreSens_P1[('mean', 'ScoreMean', 'N')]
                scoreSens_P2['ScoreSens_S_WD']  = scoreSens_P2[('mean', 'ScoreMean', 'S')] - scoreSens_P2[('mean', 'ScoreMean', 'WD')]
                scoreSens_P3['ScoreSens_S_NMS'] = scoreSens_P3[('mean', 'ScoreMean', 'S')] - scoreSens_P3[('mean', 'ScoreMean', 'NMS')]

                print("scoreSens_N_S = ",  scoreSens_P1)
                print("scoreSens_WD_S = ", scoreSens_P2)
                print("scoreSens_NMS_S = ", scoreSens_P3)

            # les paires de sous-groupes: - M_N (Malentendant / Neutre), - M_WD (Malentendant / Without Disability: sans-handicap), - M_NMS (Malentendant / Ni Sourd Ni Malentendant)
            case 'M': # Malentendant
                grN = 'M_N'
                grWD = 'M_WD'
                grNMS = 'M_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ScoreMean', 'M')] != 0)]
                scoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'M')] != 0)]
                scoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'M')] != 0)]
                # Ajout de nouvelles colonnes
                scoreSens_P1['ScoreSens_M_N'] = scoreSens_P1[('mean', 'ScoreMean', 'M')] - scoreSens_P1[('mean', 'ScoreMean', 'N')]
                scoreSens_P2['ScoreSens_M_WD'] = scoreSens_P2[('mean', 'ScoreMean', 'M')] - scoreSens_P2[('mean', 'ScoreMean', 'WD')]
                scoreSens_P3['ScoreSens_M_NMS'] = scoreSens_P3[('mean', 'ScoreMean', 'M')] - scoreSens_P3[('mean', 'ScoreMean', 'NMS')]

                print("scoreSens_N_M = ",  scoreSens_P1)
                print("scoreSens_WD_M = ", scoreSens_P2)
                print("scoreSens_NMS_M = ", scoreSens_P3)

            # les paires de sous-groupes : MS_N (Sourd et/ou Malentendant / Neutre), - MS_WD (Sourd et/ou Malentendant / Without Disability: sans-handicap), MS_NMS (Sourd et/ou Malentendant / Ni Sourd Ni Malentendant)
            case 'MS': # (Sourd et/ou Malentendant)

                grN = 'MS_N'
                grWD = 'MS_WD'
                grNMS = 'MS_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ScoreMean', 'MS')] != 0)]
                scoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'MS')] != 0)]
                scoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'MS')] != 0)]
                # Ajout de nouvelles colonnes
                scoreSens_P1['ScoreSens_MS_N']   = scoreSens_P1[('mean', 'ScoreMean', 'MS')] - scoreSens_P1[('mean', 'ScoreMean', 'N')]
                scoreSens_P2['ScoreSens_MS_WD']  = scoreSens_P2[('mean', 'ScoreMean', 'MS')] - scoreSens_P2[('mean', 'ScoreMean', 'WD')]
                scoreSens_P3['ScoreSens_MS_NMS'] = scoreSens_P3[('mean', 'ScoreMean', 'MS')] - scoreSens_P3[('mean', 'ScoreMean', 'NMS')]

                print("scoreSens_N_MS = ",  scoreSens_P1)
                print("scoreSens_WD_MS = ", scoreSens_P2)
                print("scoreSens_NMS_MS = ", scoreSens_P3)

            # les paires de sous-groupes : SA_N (Sourd-Aveugle / Neutre), - SA_WD (Sourd-Aveugle / Without Disability: sans-handicap), SA_NMS (Sourd-Aveugle / Ni Sourd Ni Malentendant)
            case 'SA': # (Sourd-Aveugle)
                grN = 'SA_N'
                grWD = 'SA_WD'
                grNMS = 'SA_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ScoreMean', 'SA')] != 0)]
                scoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'SA')] != 0)]
                scoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'SA')] != 0)]
                # Ajout de nouvelles colonnes
                scoreSens_P1['ScoreSens_SA_N']   = scoreSens_P1[('mean', 'ScoreMean', 'SA')] - scoreSens_P1[('mean', 'ScoreMean', 'N')]
                scoreSens_P2['ScoreSens_SA_WD']  = scoreSens_P2[('mean', 'ScoreMean', 'SA')] - scoreSens_P2[('mean', 'ScoreMean', 'WD')]
                scoreSens_P3['ScoreSens_SA_NMS'] = scoreSens_P3[('mean', 'ScoreMean', 'SA')] - scoreSens_P3[('mean', 'ScoreMean', 'NMS')]

                print("scoreSens_N_SA = ",  scoreSens_P1)
                print("scoreSens_WD_SA = ", scoreSens_P2)
                print("scoreSens_NMS_SA = ", scoreSens_P3)

            # les paires de sous-groupes : SP_N (Sourd-Plus / Neutre), - SP_WD (Sourd-Plus / Without Disability: sans-handicap), SP_NMS (Sourd-Plus / Ni Sourd Ni Malentendant)
            case 'SP': # (Sourd-Plus)
                grN = 'SP_N'
                grWD = 'SP_WD'
                grNMS = 'SP_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ScoreMean', 'SP')] != 0)]
                scoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'SP')] != 0)]
                scoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'SP')] != 0)]
                # Ajout de nouvelles colonnes
                scoreSens_P1['ScoreSens_SP_N']   = scoreSens_P1[('mean', 'ScoreMean', 'SP')] - scoreSens_P1[('mean', 'ScoreMean', 'N')]
                scoreSens_P2['ScoreSens_SP_WD']  = scoreSens_P2[('mean', 'ScoreMean', 'SP')] - scoreSens_P2[('mean', 'ScoreMean', 'WD')]
                scoreSens_P3['ScoreSens_SP_NMS'] = scoreSens_P3[('mean', 'ScoreMean', 'SP')] - scoreSens_P3[('mean', 'ScoreMean', 'NMS')]

                print("scoreSens_N_SP = ",  scoreSens_P1)
                print("scoreSens_WD_SP = ", scoreSens_P2)
                print("scoreSens_NMS_SP = ", scoreSens_P3)

            #case 'NS': // Non-Sourd (non encore traité)
            #case 'NM': // Non-Malentendant (non encore traité)

   return scoreSens_P1,scoreSens_P2,scoreSens_P3,grN,grWD,grNMS

# Calcul de la métrique - ScoreSens

# Parcourir la liste des fichiers -.csv (contenant les résultats fusionnés)
file_paths_results = list(Path(AllFusionMaskFiles_path).glob("*.csv"))
# par groupe : by = "G"

# par sous groupe :
by = "SG"
for file_result in file_paths_results:

    # Calcul de la métrique - ScoreSens (groupée par : Connector+Mask-CM / Connector-C / Mask-M)
    scoreSens_CM, scoreSens_C,scoreSens_M =  calculScoreSens(file_result, by)
    scoreSensP1_CM,scoreSensP2_CM,scoreSensP3_CM,gr1,gr2,gr3 = filterScoreSens(scoreSens_CM)
    scoreSensP1_C,scoreSensP2_C,scoreSensP3_C,gr1,gr2,gr3 = filterScoreSens(scoreSens_C)
    scoreSensP1_M,scoreSensP2_M,scoreSensP3_M,gr1,gr2,gr3 = filterScoreSens(scoreSens_M)
    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Transfert des résultats intermédiaires dans un fichier -.csv

      # Groupés par Connector+Mask
    outputFileNameCsvOfCM   = "metricScoreSens-by_ConnectorMask" + fileName + ".csv"
    scoreSens_CM.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfCM, sep=";", index=False)
      # Groupés par Connector
    outputFileNameCsvOfC   = "metricScoreSens-by_Connector" + fileName + ".csv"
    scoreSens_C.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfC, sep=";", index=False)
      # Groupés par mask
    outputFileNameCsvOfM   = "metricScoreSens-by_Mask" + fileName + ".csv"
    scoreSens_M.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfM, sep=";", index=False)

    # Transfert des résultats filtrés de chaque paire de sous-groupes dans un fichier -.csv

      # Groupés par Connector+Mask
    outputFileNameCsvOfP1_CM  = gr1 + "-by_ConnectorMask" + fileName + ".csv"
    outputFileNameCsvOfP2_CM  = gr2 + "-by_ConnectorMask" + fileName + ".csv"
    outputFileNameCsvOfP3_CM  = gr3 + "-by_ConnectorMask" + fileName + ".csv"

    scoreSensP1_CM.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP1_CM, sep=";", index=False)
    scoreSensP2_CM.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP2_CM, sep=";", index=False)
    scoreSensP3_CM.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP3_CM, sep=";", index=False)

      # Groupés par Connector
    outputFileNameCsvOfP1_C  = gr1 + "-by_Connector" + fileName + ".csv"
    outputFileNameCsvOfP2_C  = gr2 + "-by_Connector" + fileName + ".csv"
    outputFileNameCsvOfP3_C  = gr3 + "-by_Connector" + fileName + ".csv"

    scoreSensP1_C.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP1_C, sep=";", index=False)
    scoreSensP2_C.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP2_C, sep=";", index=False)
    scoreSensP3_C.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP3_C, sep=";", index=False)

     # Groupés par mask
    outputFileNameCsvOfP1_M  = gr1 + "-by_Mask" + fileName + ".csv"
    outputFileNameCsvOfP2_M  = gr2 + "-by_Mask" + fileName + ".csv"
    outputFileNameCsvOfP3_M  = gr3 + "-by_Mask" + fileName + ".csv"

    scoreSensP1_M.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP1_M, sep=";", index=False)
    scoreSensP2_M.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP2_M, sep=";", index=False)
    scoreSensP3_M.to_csv(metrics_ScoreSens_path  + outputFileNameCsvOfP3_M, sep=";", index=False)

    #outputFileNameExcel = "metricScoresSens-" + by + "_mlmElectra_" + fileName + ".xlsx"
    #scoreSens.to_excel(metrics_ScoreSens_path  + outputFileNameExcel, index=True)

# Fin de calcul de la métrique -ScoreSens

# Définition d'une fonction qui calcule le score de sensibilité (scoreDev) entre
# les différents groupes (ou sous-groupes) : une metrique introduite dans
# (Prabhakaran Vinodkumar et al., 2019).

def calculScoreDev(filePath,by):

    # Parcourir le fichier .csv (du dossier "AllFusionMaskFiles...") entré en parametre
    pdFusion = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    print("pdFusion / par sous-groupes = ", pdFusion)

    # les scores moyens groupés par sous groupes
    if by == "SG" :
         #print("SG-pdFusion / par sous-groupes = ", pdFusion)

         # Création du tableau dynamique croisé / fonction d'aggrégation = l'ecart type des scores
           # by connector + mask
         scoreDevRes_CM = pd.pivot_table(pdFusion,index=["connector", "mask"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc=[np.std], fill_value=0).reset_index()
           # by connector
         scoreDevRes_C = pd.pivot_table(pdFusion,index=["connector"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc=[np.std], fill_value=0).reset_index()
           # by mask
         scoreDevRes_M = pd.pivot_table(pdFusion,index=["mask"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc=[np.std], fill_value=0).reset_index()

         #print("Calcul scoreDevRes_CM = ", scoreDevRes_CM)
         #print("Calcul scoreDevRes_C = ", scoreDevRes_C)
         #print("Calcul scoreDevRes_M = ", scoreDevRes_M)

    # les scores moyens groupés par groupes
    else :
         print("pdFusion / par groupes = ", pdFusion.columns)

         # Création du tableau dynamique croisé / fonction d'aggrégation = l'ecart type des scores
           # by connector + mask
         scoreDevRes_CM = pd.pivot_table(pdFusion,index=["connector", "mask"], values=["ScoreMean"], columns=["groupe"], aggfunc=[np.std], fill_value=0).reset_index()
           # by connector
         scoreDevRes_C = pd.pivot_table(pdFusion,index=["connector"], values=["ScoreMean"], columns=["groupe"], aggfunc=[np.std], fill_value=0).reset_index()
           # by mask
         scoreDevRes_M = pd.pivot_table(pdFusion,index=["mask"], values=["ScoreMean"], columns=["groupe"], aggfunc=[np.std], fill_value=0).reset_index()

         #print("scoreDevRes_CM = ", scoreDevRes_CM.columns)
         #print("scoreDevRes_C = ", scoreDevRes_C.columns)
         #print("scoreDevRes_M = ", scoreDevRes_M.columns)

    return scoreDevRes_CM,scoreDevRes_C,scoreDevRes_M

# Définition d'une fonction qui filtre le résultat de la fonction
# - CalculScoreDev pour faciliter le calcul

def filterScoreDev(pdFile):

   scoreDev_P1 = []
   scoreDev_P2 = []
   scoreDev_P3 = []
   #sgr = ''
   # Parcourir le fichier .csv entré en parametre
   pdFileToFilter = pdFile

   # parcourir la liste des noms des colonnes
   for m,s,g in pdFileToFilter.columns.values:

       print("Sous-groupes = ", g)
       match g:
            # les paires de sous-groupes : S_N (Sourd / Neutre), - S_WD (Sourd / Without Disability: sans-handicap), S_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'S': # Sourd
                grN = 'S_N'
                grWD = 'S_WD'
                grNMS = 'S_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ScoreMean', 'S')] != 0)]
                scoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'S')] != 0)]
                scoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'S')] != 0)]
                scoreDev_P1['ScoreDev_S_N'] = scoreDev_P1[('std', 'ScoreMean', 'S')] - scoreDev_P1[('std', 'ScoreMean', 'N')]
                scoreDev_P2['ScoreDev_S_WD'] = scoreDev_P2[('std', 'ScoreMean', 'S')] - scoreDev_P2[('std', 'ScoreMean', 'WD')]
                scoreDev_P3['ScoreDev_S_NMS'] = scoreDev_P3[('std', 'ScoreMean', 'S')] - scoreDev_P3[('std', 'ScoreMean', 'NMS')]

                print("scoreDev_N_S = ",  scoreDev_P1)
                print("scoreDev_WD_S = ", scoreDev_P2)
                print("scoreDev_NMS_S = ", scoreDev_P3)

            # # les paires de sous-groupes: - M_N (Malentendant / Neutre), - M_WD (Malentendant / Without Disability: sans-handicap), - M_NMS (Malentendant / Ni Sourd Ni Malentendant)
            case 'M': # Malentendant
                grN = 'M_N'
                grWD = 'M_WD'
                grNMS = 'M_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ScoreMean', 'M')] != 0)]
                scoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'M')] != 0)]
                scoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'M')] != 0)]
                scoreDev_P1['ScoreDev_M_N'] = scoreDev_P1[('std', 'ScoreMean', 'M')] - scoreDev_P1[('std', 'ScoreMean', 'N')]
                scoreDev_P2['ScoreDev_M_WD'] = scoreDev_P2[('std', 'ScoreMean', 'M')] - scoreDev_P2[('std', 'ScoreMean', 'WD')]
                scoreDev_P3['ScoreDev_M_NMS'] = scoreDev_P3[('std', 'ScoreMean', 'M')] - scoreDev_P3[('std', 'ScoreMean', 'NMS')]

                print("scoreDev_N_M = ",  scoreDev_P1)
                print("scoreDev_WD_M = ", scoreDev_P2)
                print("scoreDev_NMS_M = ", scoreDev_P3)

            # les paires de sous-groupes : MS_N (Sourd et/ou Malentendant / Neutre), - MS_WD (Sourd et/ou Malentendant / Without Disability: sans-handicap), MS_NMS (Sourd et/ou Malentendant / Ni Sourd Ni Malentendant)
            case 'MS': # (Sourd et/ou Malentendant)
                grN = 'MS_N'
                grWD = 'MS_WD'
                grNMS = 'MS_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ScoreMean', 'MS')] != 0)]
                scoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'MS')] != 0)]
                scoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'MS')] != 0)]
                scoreDev_P1['ScoreDev_MS_N'] = scoreDev_P1[('std', 'ScoreMean', 'MS')] - scoreDev_P1[('std', 'ScoreMean', 'N')]
                scoreDev_P2['ScoreDev_MS_WD'] = scoreDev_P2[('std', 'ScoreMean', 'MS')] - scoreDev_P2[('std', 'ScoreMean', 'WD')]
                scoreDev_P3['ScoreDev_MS_NMS'] = scoreDev_P3[('std', 'ScoreMean', 'MS')] - scoreDev_P3[('std', 'ScoreMean', 'NMS')]

                print("scoreDev_N_MS = ",  scoreDev_P1)
                print("scoreDev_WD_MS = ", scoreDev_P2)
                print("scoreDev_NMS_MS = ", scoreDev_P3)

            # les paires de sous-groupes : SA_N (Sourd-Aveugle / Neutre), - SA_WD (Sourd-Aveugle / Without Disability: sans-handicap), SA_NMS (Sourd-Aveugle / Ni Sourd Ni Malentendant)
            case 'SA': # (Sourd-Aveugle)
                grN = 'SA_N'
                grWD = 'SA_WD'
                grNMS = 'SA_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ScoreMean', 'SA')] != 0)]
                scoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'SA')] != 0)]
                scoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'SA')] != 0)]
                scoreDev_P1['ScoreDev_SA_N'] = scoreDev_P1[('std', 'ScoreMean', 'SA')] - scoreDev_P1[('std', 'ScoreMean', 'N')]
                scoreDev_P2['ScoreDev_SA_WD'] = scoreDev_P2[('std', 'ScoreMean', 'SA')] - scoreDev_P2[('std', 'ScoreMean', 'WD')]
                scoreDev_P3['ScoreDev_SA_NMS'] = scoreDev_P3[('std', 'ScoreMean', 'SA')] - scoreDev_P3[('std', 'ScoreMean', 'NMS')]

                print("scoreDev_N_SA = ",  scoreDev_P1)
                print("scoreDev_WD_SA = ", scoreDev_P2)
                print("scoreDev_NMS_SA = ", scoreDev_P3)

            # les paires de sous-groupes : SP_N (Sourd-Plus / Neutre), - SP_WD (Sourd-Plus / Without Disability: sans-handicap), SP_NMS (Sourd-Plus / Ni Sourd Ni Malentendant)
            case 'SP': # (Sourd-Plus)
                grN = 'SP_N'
                grWD = 'SP_WD'
                grNMS = 'SP_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ScoreMean', 'SP')] != 0)]
                scoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'SP')] != 0)]
                scoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ScoreMean', 'SP')] != 0)]
                scoreDev_P1['ScoreDev_SP_N'] = scoreDev_P1[('std', 'ScoreMean', 'SP')] - scoreDev_P1[('std', 'ScoreMean', 'N')]
                scoreDev_P2['ScoreDev_SP_WD'] = scoreDev_P2[('std', 'ScoreMean', 'SP')] - scoreDev_P2[('std', 'ScoreMean', 'WD')]
                scoreDev_P3['ScoreDev_SP_NMS'] = scoreDev_P3[('std', 'ScoreMean', 'SP')] - scoreDev_P3[('std', 'ScoreMean', 'NMS')]

                print("scoreDev_N_SP = ",  scoreDev_P1)
                print("scoreDev_WD_SP = ", scoreDev_P2)
                print("scoreDev_NMS_SP = ", scoreDev_P3)

            #case 'NS': // Non-Sourd (encore traité)
            #case 'NM': // Non-Malentendant (encore traité)

   return scoreDev_P1,scoreDev_P2,scoreDev_P3,grN,grWD,grNMS

# Calcul de la métrique - ScoreDev

# Parcourir la liste des fichiers -.csv (contenant les résultats fusionnés)
file_paths_results = list(Path(AllFusionMaskFiles_path).glob("*.csv"))
# par groupe : by = "G"

# par sous groupe :
by = "SG"
for file_result in file_paths_results:

    #print("file_result = ",file_result)

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Calcul de la métrique - ScoreDev (groupée par : Connector+Mask-CM / Connector-C / Mask-M)
    scoreDev_CM,scoreDev_C,scoreDev_M  =  calculScoreDev(file_result, by)

    # Transfert des résultats dans un fichier -.csv

      # Groupés par Connector+Mask
    outputFileNameCsv_CM   = "metricScoreDev-by_ConnectorMask" + fileName + ".csv"
    scoreDev_CM.to_csv(metrics_ScoreDev_path  + outputFileNameCsv_CM, sep=";", index=False)

      # Groupés par Connector
    outputFileNameCsv_C   = "metricScoreDev-by_Connector" + fileName + ".csv"
    scoreDev_C.to_csv(metrics_ScoreDev_path  + outputFileNameCsv_C, sep=";", index=False)
      # Groupés par Mask
    outputFileNameCsv_M   = "metricScoreDev-by_Mask" + fileName + ".csv"
    scoreDev_M.to_csv(metrics_ScoreDev_path  + outputFileNameCsv_M, sep=";", index=False)

    # Filter et Transferer les résultats filtrés de chaque paire de sous-groupes dans un fichier -.csv

      # Groupés par Connector+Mask
    if (scoreDev_CM.size != 0 ):

      scoreDevP1_CM,scoreDevP2_CM,scoreDevP3_CM,gr1,gr2,gr3 = filterScoreDev(scoreDev_CM)

      #print("Groupés par Connector+Mask: gr1 = ",gr1," gr2 = ",gr2," gr3 = ",gr3)

      outputFileNameCsvOfP1_CM = gr1 + "-by_ConnectorMask" + fileName + ".csv"
      outputFileNameCsvOfP2_CM = gr2 + "-by_ConnectorMask" + fileName + ".csv"
      outputFileNameCsvOfP3_CM = gr3 + "-by_ConnectorMask" + fileName + ".csv"

      scoreDevP1_CM.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP1_CM, sep=";", index=False)
      scoreDevP2_CM.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP2_CM, sep=";", index=False)
      scoreDevP3_CM.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP3_CM, sep=";", index=False)

      # Groupés par Connector
    if (scoreDev_C.size  != 0 ):
      scoreDevP1_C,scoreDevP2_C,scoreDevP3_C,gr1,gr2,gr3 = filterScoreDev(scoreDev_C)
      #print("Groupés par Connector: gr1 = ",gr1," gr2 = ",gr2," gr3 = ",gr3)

      outputFileNameCsvOfP1_C = gr1 + "-by_Connector" + fileName + ".csv"
      outputFileNameCsvOfP2_C = gr2 + "-by_Connector" + fileName + ".csv"
      outputFileNameCsvOfP3_C = gr3 + "-by_Connector" + fileName + ".csv"

      scoreDevP1_C.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP1_C, sep=";", index=False)
      scoreDevP2_C.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP2_C, sep=";", index=False)
      scoreDevP3_C.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP3_C, sep=";", index=False)

     # Groupés par Mask
    if (scoreDev_M.size  != 0 ):
      scoreDevP1_M,scoreDevP2_M,scoreDevP3_M,gr1,gr2,gr3 = filterScoreDev(scoreDev_M)
      #print("Groupés par Mask: gr1 = ",gr1," gr2 = ",gr2," gr3 = ",gr3)

      outputFileNameCsvOfP1_M = gr1 + "-by_Mask" + fileName + ".csv"
      outputFileNameCsvOfP2_M = gr2 + "-by_Mask" + fileName + ".csv"
      outputFileNameCsvOfP3_M = gr3 + "-by_Mask" + fileName + ".csv"

      scoreDevP1_M.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP1_M, sep=";", index=False)
      scoreDevP2_M.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP2_M, sep=";", index=False)
      scoreDevP3_M.to_csv(metrics_ScoreDev_path  + outputFileNameCsvOfP3_M, sep=";", index=False)


    #outputFileNameExcel = "metricScoresDev-" + by + "_mlmElectraPredict_" + fileName + ".xlsx"
    #scoreSens.to_excel(metrics_ScoreDev_path  + outputFileNameExcel, index=True)

# Fin de calcul de la métrique -ScoreDev

# Définition d'une fonction qui calcule le score de sensibilité (scoreRange: Min-Max)
# entre les différents groupes (ou sous-groupes) : une metrique introduite dans
# (Prabhakaran Vinodkumar et al., 2019).

def calculScoreRange(filePath,by):

    # Parcourir le fichier .csv (du dossier "AllFusionMaskFiles...") entré en parametre
    pdFusion = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # les scores moyens groupés par sous groupes
    if by == "SG" :
         #print("SG-pdFusion / par sous-groupes = ", pdFusion)

         # Création du tableau dynamique croisé / fonction d'aggrégation = min-max des scores

           # by connector + mask
         scoreRangeRes_CM = pd.pivot_table(pdFusion,index=["connector", "mask"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
           # by connector
         scoreRangeRes_C = pd.pivot_table(pdFusion,index=["connector"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
           # by mask
         scoreRangeRes_M = pd.pivot_table(pdFusion,index=["mask"], values=["ScoreMean"], columns=["sousGroupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()

         print("scoreRangeRes_CM = ", scoreRangeRes_CM.columns)
         print("scoreRangeRes_C = ", scoreRangeRes_C.columns)
         print("scoreRangeRes_M = ", scoreRangeRes_M.columns)

    # les scores moyens groupés par groupes
    else :
         print("pdFusion / par groupes = ", pdFusion.columns)

         # Création du tableau dynamique croisé / fonction d'aggrégation = min-max des scores

           # by connector + mask
         scoreRangeRes_CM = pd.pivot_table(pdFusion,index=["connector", "mask"], values=["ScoreMean"], columns=["groupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
           # by connector
         scoreRangeRes_C = pd.pivot_table(pdFusion,index=["connector"], values=["ScoreMean"], columns=["groupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
           # by mask
         scoreRangeRes_M = pd.pivot_table(pdFusion,index=["mask"], values=["ScoreMean"], columns=["groupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()

         print("scoreRangeRes_CM = ", scoreRangeRes_CM.columns)
         print("scoreRangeRes_C = ", scoreRangeRes_C.columns)
         print("scoreRangeRes_M = ", scoreRangeRes_M.columns)

    return scoreRangeRes_CM,scoreRangeRes_C,scoreRangeRes_M

# Définition d'une fonction qui filtre le résultat de la fonction
# - CalculScoreRange pour faciliter le calcul

def filterScoreRange(pdFile):

   scoreRange_P1 = []
   scoreRange_P2 = []
   scoreRange_P3 = []
   #sgr = ''
   # Parcourir le fichier .csv entré en parametre
   pdFileToFilter = pdFile

   # parcourir la liste des noms des colonnes
   for m,s,g in pdFileToFilter.columns.values:
       match g:
            # les paires de sous-groupes : S_N (Sourd / Neutre), - S_WD (Sourd / Without Disability: sans-handicap), S_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'S':
                grN = 'S_N'
                grWD = 'S_WD'
                grNMS = 'S_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'S')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'S')] != 0)]
                scoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'S')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'S')] != 0)]
                scoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'S')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'S')] != 0)]

                # Agrégat = Max
                scoreRange_P1['ScoreMax_S_N']   = scoreRange_P1[('max', 'ScoreMean', 'S')] - scoreRange_P1[('max', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMax_S_WD']  = scoreRange_P2[('max', 'ScoreMean', 'S')] - scoreRange_P2[('max', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMax_S_NMS'] = scoreRange_P3[('max', 'ScoreMean', 'S')] - scoreRange_P3[('max', 'ScoreMean', 'NMS')]

                # Agrégat = Min
                scoreRange_P1['ScoreMin_S_N']   = scoreRange_P1[('min', 'ScoreMean', 'S')] - scoreRange_P1[('min', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMin_S_WD']  = scoreRange_P2[('min', 'ScoreMean', 'S')] - scoreRange_P2[('min', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMin_S_NMS'] = scoreRange_P3[('min', 'ScoreMean', 'S')] - scoreRange_P3[('min', 'ScoreMean', 'NMS')]

                print("scoreRange_N_S = ",   scoreRange_P1)
                print("scoreRange_WD_S = ",  scoreRange_P2)
                print("scoreRange_NMS_S = ", scoreRange_P3)

            # les deux paires de sous-groupes - M_N (Malentendant / Neutre) et - M_WD (Malentendant / Without Disability)
            case 'M':
                grN = 'M_N'
                grWD = 'M_WD'
                grNMS = 'M_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'M')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'M')] != 0)]
                scoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'M')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'M')] != 0)]
                scoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'M')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'M')] != 0)]

                # Agrégat = Max
                scoreRange_P1['ScoreMax_M_N']   = scoreRange_P1[('max', 'ScoreMean', 'M')] - scoreRange_P1[('max', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMax_M_WD']  = scoreRange_P2[('max', 'ScoreMean', 'M')] - scoreRange_P2[('max', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMax_M_NMS'] = scoreRange_P3[('max', 'ScoreMean', 'M')] - scoreRange_P3[('max', 'ScoreMean', 'NMS')]

                # Agrégat = Min
                scoreRange_P1['ScoreMin_M_N']   = scoreRange_P1[('min', 'ScoreMean', 'M')] - scoreRange_P1[('min', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMin_M_WD']  = scoreRange_P2[('min', 'ScoreMean', 'M')] - scoreRange_P2[('min', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMin_M_NMS'] = scoreRange_P3[('min', 'ScoreMean', 'M')] - scoreRange_P3[('min', 'ScoreMean', 'NMS')]

                print("scoreRange_N_M = ",  scoreRange_P1)
                print("scoreRange_WD_M = ", scoreRange_P2)
                print("scoreRange_NMS_M = ", scoreRange_P3)

            # les paires de sous-groupes : MS_N (Sourd et/ou Malentendant / Neutre), - MS_WD (Sourd et/ou Malentendant / Without Disability: sans-handicap), MS_NMS (Sourd et/ou Malentendant / Ni Sourd Ni Malentendant)
            case 'MS': # (Sourd et/ou Malentendant)
                grN = 'MS_N'
                grWD = 'MS_WD'
                grNMS = 'MS_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'MS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'MS')] != 0)]
                scoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'MS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'MS')] != 0)]
                scoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'MS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'MS')] != 0)]

                # Agrégat = Max
                scoreRange_P1['ScoreMax_MS_N']   = scoreRange_P1[('max', 'ScoreMean', 'MS')] - scoreRange_P1[('max', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMax_MS_WD']  = scoreRange_P2[('max', 'ScoreMean', 'MS')] - scoreRange_P2[('max', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMax_MS_NMS'] = scoreRange_P3[('max', 'ScoreMean', 'MS')] - scoreRange_P3[('max', 'ScoreMean', 'NMS')]

                # Agrégat = Min
                scoreRange_P1['ScoreMin_MS_N']   = scoreRange_P1[('min', 'ScoreMean', 'MS')] - scoreRange_P1[('min', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMin_MS_WD']  = scoreRange_P2[('min', 'ScoreMean', 'MS')] - scoreRange_P2[('min', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMin_MS_NMS'] = scoreRange_P3[('min', 'ScoreMean', 'MS')] - scoreRange_P3[('min', 'ScoreMean', 'NMS')]

                print("scoreRange_N_MS = ",  scoreRange_P1)
                print("scoreRange_WD_MS = ", scoreRange_P2)
                print("scoreRange_NMS_MS = ", scoreRange_P3)

            # les paires de sous-groupes : SA_N (Sourd-Aveugle / Neutre), - SA_WD (Sourd-Aveugle / Without Disability: sans-handicap), SA_NMS (Sourd-Aveugle / Ni Sourd Ni Malentendant)
            case 'SA': # (Sourd-Aveugle)
                grN = 'SA_N'
                grWD = 'SA_WD'
                grNMS = 'SA_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'SA')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'SA')] != 0)]
                scoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'SA')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'SA')] != 0)]
                scoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'SA')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'SA')] != 0)]

                # Agrégat = Max
                scoreRange_P1['ScoreMax_SA_N']    = scoreRange_P1[('max', 'ScoreMean', 'SA')] - scoreRange_P1[('max', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMax_SA_WD']   = scoreRange_P2[('max', 'ScoreMean', 'SA')] - scoreRange_P2[('max', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMax_SA_NMS']  = scoreRange_P3[('max', 'ScoreMean', 'SA')] - scoreRange_P3[('max', 'ScoreMean', 'NMS')]

                # Agrégat = Min
                scoreRange_P1['ScoreMin_SA_N']   = scoreRange_P1[('min', 'ScoreMean', 'SA')] - scoreRange_P1[('min', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMin_SA_WD']  = scoreRange_P2[('min', 'ScoreMean', 'SA')] - scoreRange_P2[('min', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMin_SA_NMS'] = scoreRange_P3[('min', 'ScoreMean', 'SA')] - scoreRange_P3[('min', 'ScoreMean', 'NMS')]

                print("scoreRange_N_SA = ",   scoreRange_P1)
                print("scoreRange_WD_SA = ",  scoreRange_P2)
                print("scoreRange_NMS_SA = ", scoreRange_P3)


            # les paires de sous-groupes : SP_N (Sourd-Plus / Neutre), - SP_WD (Sourd-Plus / Without Disability: sans-handicap), SP_NMS (Sourd-Plus / Ni Sourd Ni Malentendant)
            case 'SP': # (Sourd-Plus)
                grN = 'SP_N'
                grWD = 'SP_WD'
                grNMS = 'SP_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                scoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'N')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'SP')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'SP')] != 0)]
                scoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'SP')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'SP')] != 0)]
                scoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ScoreMean', 'SP')] != 0) & (pdFileToFilter[('min', 'ScoreMean', 'SP')] != 0)]

                # Agrégat = Max
                scoreRange_P1['ScoreMax_SP_N']   = scoreRange_P1[('max', 'ScoreMean', 'SP')] - scoreRange_P1[('max', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMax_SP_WD']  = scoreRange_P2[('max', 'ScoreMean', 'SP')] - scoreRange_P2[('max', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMax_SP_NMS'] = scoreRange_P3[('max', 'ScoreMean', 'SP')] - scoreRange_P3[('max', 'ScoreMean', 'NMS')]

                # Agrégat = Min
                scoreRange_P1['ScoreMin_SP_N']   = scoreRange_P1[('min', 'ScoreMean', 'SP')] - scoreRange_P1[('min', 'ScoreMean', 'N')]
                scoreRange_P2['ScoreMin_SP_WD']  = scoreRange_P2[('min', 'ScoreMean', 'SP')] - scoreRange_P2[('min', 'ScoreMean', 'WD')]
                scoreRange_P3['ScoreMin_SP_NMS'] = scoreRange_P3[('min', 'ScoreMean', 'SP')] - scoreRange_P3[('min', 'ScoreMean', 'NMS')]

                print("scoreRange_N_SP = ",   scoreRange_P1)
                print("scoreRange_WD_SP = ",  scoreRange_P2)
                print("scoreRange_NMS_SP = ", scoreRange_P3)


            #case 'NS': // Non-Sourd (non encore traité)
            #case 'NM': // Non-Malentendant (non encore traité)

   return scoreRange_P1,scoreRange_P2,scoreRange_P3,grN,grWD,grNMS

# Calcul de la métrique - ScoreRange

# Parcourir la liste des fichiers -.csv (contenant les résultats fusionnés)
file_paths_results = list(Path(AllFusionMaskFiles_path).glob("*.csv"))
# par groupe : by = "G"

# par sous groupe :
by = "SG"
for file_result in file_paths_results:

    scoreRange_CM,scoreRange_C,scoreRange_M  =  calculScoreRange(file_result, by)
    scoreRangeP1_CM,scoreRangeP2_CM,scoreRangeP3_CM,gr1,gr2,gr3 = filterScoreRange(scoreRange_CM)
    scoreRangeP1_C,scoreRangeP2_C,scoreRangeP3_C,gr1,gr2,gr3 = filterScoreRange(scoreRange_C)
    scoreRangeP1_M,scoreRangeP2_M,scoreRangeP3_M,gr1,gr2,gr3 = filterScoreRange(scoreRange_M)

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Transfert des résultats dans un fichier -.csv

      # Groupés par Connector+Mask
    outputFileNameCsv_CM   = "metricScoreRange-by_ConnectorMask" + fileName + ".csv"
    scoreRange_CM.to_csv(metrics_ScoreRange_path  + outputFileNameCsv_CM, sep=";", index=False)

      # Groupés par Connector
    outputFileNameCsv_C   = "metricScoreRange-by_Connector" + fileName + ".csv"
    scoreRange_C.to_csv(metrics_ScoreRange_path  + outputFileNameCsv_C, sep=";", index=False)

      # Groupés par Mask
    outputFileNameCsv_M   = "metricScoreRange-by_Mask" + fileName + ".csv"
    scoreRange_M.to_csv(metrics_ScoreRange_path  + outputFileNameCsv_M, sep=";", index=False)


    # Transfert des résultats filtrés de chaque paire de sous-groupes ((sgr,N) / (sgr,WD)) dans un fichier -.csv

      # Groupés par Connector+Mask
    outputFileNameCsvOfP1_CM = gr1 + "-by_ConnectorMask" + fileName + ".csv"
    outputFileNameCsvOfP2_CM = gr2 + "-by_ConnectorMask" + fileName + ".csv"
    outputFileNameCsvOfP3_CM = gr3 + "-by_ConnectorMask" + fileName + ".csv"

    scoreRangeP1_CM.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP1_CM, sep=";", index=False)
    scoreRangeP2_CM.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP2_CM, sep=";", index=False)
    scoreRangeP3_CM.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP3_CM, sep=";", index=False)

      # Groupés par Connector
    outputFileNameCsvOfP1_C = gr1 + "-by_Connector" + fileName + ".csv"
    outputFileNameCsvOfP2_C = gr2 + "-by_Connector" + fileName + ".csv"
    outputFileNameCsvOfP3_C = gr3 + "-by_Connector" + fileName + ".csv"

    scoreRangeP1_C.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP1_C, sep=";", index=False)
    scoreRangeP2_C.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP2_C, sep=";", index=False)
    scoreRangeP3_C.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP3_C, sep=";", index=False)

      # Groupés par Mask
    outputFileNameCsvOfP1_M = gr1 + "-by_Mask" + fileName + ".csv"
    outputFileNameCsvOfP2_M = gr2 + "-by_Mask" + fileName + ".csv"
    outputFileNameCsvOfP3_M = gr3 + "-by_Mask" + fileName + ".csv"

    scoreRangeP1_M.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP1_M, sep=";", index=False)
    scoreRangeP2_M.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP2_M, sep=";", index=False)
    scoreRangeP3_M.to_csv(metrics_ScoreRange_path  + outputFileNameCsvOfP3_M, sep=";", index=False)

    #outputFileNameExcel = "metricScoresRange-" + by + "_mlmElectraPredict_" + fileName + ".xlsx"
    #scoreSens.to_excel(metrics_ScoreRange_path  + outputFileNameExcel, index=True)

# Fin de calcul de la métrique -ScoreRange

# La partie du code de la fusion - des masques

# Définition d'une fonction qui fusionne les trois masques prédits par le Mlm-Electra-Large
# en faisant la moyenne des scores de probabilté regroupés par la valeur du masque
# et puis retourne le résultat dans un objet Dataframe

def fusionMasks(filePath):

    # Parcourir le fichier .csv entré en parametre
    mlmPredPd = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # extraire toutes les colonnes et les trois masks et leurs probabilités de prédiction séparemment
    fMask1 = mlmPredPd[['groupe', 'sousGroupe', 'connector' , 'spaceHolder', 'categorie', 'reference','mask1', 'score1']]
    fMask2 = mlmPredPd[['groupe', 'sousGroupe', 'connector' , 'spaceHolder', 'categorie', 'reference','mask2', 'score2']]
    fMask3 = mlmPredPd[['groupe', 'sousGroupe', 'connector' , 'spaceHolder', 'categorie', 'reference','mask3', 'score3']]

    # renommer les colonnes
    fMask1 = fMask1.rename(columns={"mask1": "mask", "score1": "score" })
    fMask2 = fMask2.rename(columns={"mask2": "mask", "score2": "score" })
    fMask3 = fMask3.rename(columns={"mask3": "mask", "score3": "score" })

    # fusionner les trois dataframes précedents
    frames = [fMask1, fMask2, fMask3]
    fusionRes = pd.concat(frames)
    # print(fusionRes)

    # Group by : référence, connecteur, groupe, sous-groupe et mask
    by = "SG"
    pdTemp = fusionRes.groupby(['reference', 'connector', 'groupe', 'sousGroupe', 'mask'])['score'].mean().reset_index(name='ScoreMean')

    # Group by : référence, connecteur, groupe et mask
    # by = "G"
    # pdTemp = fusionRes.groupby(['reference', 'connecteur', 'groupe', 'mask'])['score'].mean().reset_index(name='scoreMean')


    return pdTemp,by

# Fusion des trois jetons prédits par le MLM-Electra-Large et enregistrement des
# résultats dans des fichiers -.csv et -.xslx

# Parcourir la liste des fichiers -.csv (les prédictions du MLM-Electra-Large)
file_paths_results = list(Path(predictMlm_path).glob("*.csv"))

for file_result in file_paths_results:

    fusionRes,by  = fusionMasks(file_result)

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # concatener (le nom du fichier + l'extention -.csv ou -.excel)

    #outputFileNameCsv   = "fusionScoresMean-"+ by + "_mlmElectra_" + fileName + ".csv"
    #outputFileNameExcel = "fusionScoresMean-"+ by + "_mlmElectraPredict_" + fileName + ".xlsx"

    # Enregistrement des résultats dans un fichier -.csv/-.xlsx.
    #fusionRes.to_csv(fusionMask_path + outputFileNameCsv, sep=";", index=False)
    #fusionRes.to_excel(fusionMask_path + outputFileNameExcel, index=False)

# Fusion des fichiers -.csv du repertoire -fusionMask (de chaque groupe & sous groupe)
# dans un même fichier -.csv (tous les groupes & sous groupes)

# Parcourir la liste des fichiers -.csv du repertoire -fusionMask
file_paths_fusions = list(Path(fusionMask_path).glob("*.csv"))
pdPred = pd.Series()

# fusionner les dataframes (de chaque groupe & sous groupe)
for file_fusion in file_paths_fusions:

    pdFusionFile = pd.read_csv(file_fusion,sep=";", skipinitialspace=True)

    if pdPred.empty : frames = [pdFusionFile]
    else : frames = [pdPred,pdFusionFile]

    fusionRes = pd.concat(frames)
    pdPred = fusionRes

# Transfert des résultats dans un fichier -csv/excel.

# résultats en cours
#outputFileNameCsv = "AllFusionMaskFiles_MS_NMS_N_WD" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_SA_NMS_N_WD" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_SP_NMS_N_WD" + ".csv"

# a refaire
#outputFileNameCsv = "AllFusionMaskFiles_S_NMS_N_WD" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_M_NMS_N_WD" + ".csv"

# premiers résultats intermédiaires
#outputFileNameCsv = "AllFusionMaskFiles_N_WD_S" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_N_WD_M" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_N_WD_NM" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_N_WD_NS" + ".csv"

# Enregistrement des résultats dans un fichier -.csv
#pdPred.to_csv(AllFusionMaskFiles_path  + outputFileNameCsv, sep=";", index=False)

# Fin de la fusion

# Définition d'une fonction qui supprime les doublons

def supprimerDoublons(pdSerie):

    pdSet = pdSerie.drop_duplicates()

    return pdSet