# -*- coding: utf-8 -*-
"""HandicapBiasDetectionEmotionClassifier_01Juin2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUdrAtckZizlGBQ_R2YoZiRPFNghqnSj
"""

# Le programme de détection du biais de handicap dans le classificateur de texte (EmotionClassifier)
# calcul des metriques : -ScoreSens, ScoreDev, ScoreRange (Prabhakaran Vinodkumar et al., 2019)
# Analyse des résultats: les scores de probabilités des etiquettes d'EmotionElectraClassifier
# Dernière modification: 11 Février 2025

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

#scoresEmotionElectra_path = '/content/drive/MyDrive/ToDo/'
#scoresEmotionElectra_path = '/content/drive/MyDrive/scoresEmotionClassifier/'

#fusionMasks_path = '/content/drive/MyDrive/ToDo/'
#fusionMasks_path = '/content/drive/MyDrive/fusionMasks_EmotionClassifier/'
AllFusionMasks_path = '/content/drive/MyDrive/AllFusionMasks_EmotionClassifier/'
#metric_ScoreSens_path = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/ScoreSensEmotionClassifier/'
#metric_ScoreDev_path  = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/ScoreDevEmotionClassifier/'
metric_ScoreRange_path  = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/ScoreRangeEmotionClassifier/'

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from pathlib import Path
import torch

# import seaborn as sns
# from tqdm.auto import tqdm
# tqdm.pandas()

# emotion_categories = ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# torch.device("cuda:0")
#device = torch.device("cuda")

# Définition d'une fonction qui supprime les doublons

def supprimerDoublons(pdSerie):

    pdSet = pdSerie.drop_duplicates()

    return pdSet

# Définition d'une fonction qui calcule le score de sensibilité (la probabilité de prédiction
# de l'etiquette d'émotion) entre les différents groupes (ou sous-groupes) : la metrique - ScoreSens
# (Prabhakaran Vinodkumar et al., 2019).

def calculProbabilityScoreSens(filePath,by):

    # Parcourir le fichier .csv (du dossier "AllFusionMaskFiles...") entré en parametre
    pdFusion = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # les scores moyens groupés par sous groupes
    if by == "SG" :
         #print("SG-pdFusion / par sous-groupes = ", pdFusion)

         # Création du tableau dynamique croisé / fonction d'aggrégation = la moyenne des scores
         # de prediction des étiquettes (ou labels) d'emotion

             # by connector + mask + label
         ProbabilityScoreSensRes_CML = pd.pivot_table(pdFusion,index=["connector", "mask", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.mean], fill_value=0).reset_index()
             # by connector + label
         ProbabilityScoreSensRes_CL  = pd.pivot_table(pdFusion,index=["connector", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.mean], fill_value=0).reset_index()
             # by mask + label
         ProbabilityScoreSensRes_ML  = pd.pivot_table(pdFusion,index=["mask", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.mean], fill_value=0).reset_index()
             # by label
         ProbabilityScoreSensRes_L   = pd.pivot_table(pdFusion,index=["label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.mean], fill_value=0).reset_index()

    # les scores moyens groupés par groupes
    else :
         print("pdFusion / par groupes = ", pdFusion.columns)

         # Création du tableau dynamique croisé / fonction d'aggrégation = la moyenne des scores

              # by connector + mask + label
         ProbabilityScoreSensRes_CML = pd.pivot_table(pdFusion,index=["connector", "mask", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.mean], fill_value=0).reset_index()
              # by connector + label
         ProbabilityScoreSensRes_CL = pd.pivot_table(pdFusion,index=["connector", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.mean], fill_value=0).reset_index()
              # by mask + label
         ProbabilityScoreSensRes_ML = pd.pivot_table(pdFusion,index=["mask", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.mean], fill_value=0).reset_index()
              # by label
         ProbabilityScoreSensRes_L = pd.pivot_table(pdFusion,index=["label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.mean], fill_value=0).reset_index()


         #print("ProbabilityScoreSensRes_CML = ", ProbabilityScoreSensRes_CML.columns)

    return ProbabilityScoreSensRes_CML,ProbabilityScoreSensRes_CL,ProbabilityScoreSensRes_ML,ProbabilityScoreSensRes_L

# Définition d'une fonction qui filtre le résultat de la fonction - CalculScoreSens
# pour faciliter le calcul

def filterProbabilityScoreSens(pdFile):

   ProbabilityScoreSens_P1 = []
   ProbabilityScoreSens_P2 = []
   ProbabilityScoreSens_P3 = []

   # sgr = ''
   # Parcourir le fichier .csv entré en parametre
   pdFileToFilter = pdFile

   # parcourir la liste des noms des colonnes
   for m,s,g in pdFileToFilter.columns.values:
       match g:
            # les paires de sous-groupes - S_N (Sourd / Neutre) , - S_WD (Sourd / Without Disability), -S_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'S': # Sourd
                grN = 'S_N'
                grWD = 'S_WD'
                grNMS = 'S_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreSens_P1 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreSens_P2 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreSens_P3 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreSens_P1['ProbabilitySens_S_N']   = ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'S')] - ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'N')]
                ProbabilityScoreSens_P2['ProbabilitySens_S_WD']  = ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'S')] - ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'WD')]
                ProbabilityScoreSens_P3['ProbabilitySens_S_NMS'] = ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'S')] - ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreSens_N_S = ",   ProbabilityScoreSens_P1)
                print("ProbabilityScoreSens_WD_S = ",  ProbabilityScoreSens_P2)
                print("ProbabilityScoreSens_NMS_S = ", ProbabilityScoreSens_P3)

            # les paires de sous-groupes - M_N (Malentendant / Neutre) , - M_WD (Malentendant / Without Disability), -M_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'M': # Malentendant
                grN = 'M_N'
                grWD = 'M_WD'
                grNMS = 'M_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreSens_P1['ProbabilitySens_M_N']   = ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'M')] - ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'N')]
                ProbabilityScoreSens_P2['ProbabilitySens_M_WD']  = ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'M')] - ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'WD')]
                ProbabilityScoreSens_P3['ProbabilitySens_M_NMS'] = ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'M')] - ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreSens_N_M = ",  ProbabilityScoreSens_P1)
                print("ProbabilityScoreSens_WD_M = ", ProbabilityScoreSens_P2)
                print("ProbabilityScoreSens_NMS_M = ", ProbabilityScoreSens_P3)

            # les paires de sous-groupes : MS_N (Sourd et/ou Malentendant / Neutre), - MS_WD (Sourd et/ou Malentendant / Without Disability: sans-handicap), MS_NMS (Sourd et/ou Malentendant / Ni Sourd Ni Malentendant)
            case 'MS': # (Sourd et/ou Malentendant)
                grN = 'MS_N'
                grWD = 'MS_WD'
                grNMS = 'MS_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreSens_P1['ProbabilitySens_MS_N']   = ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'MS')] - ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'N')]
                ProbabilityScoreSens_P2['ProbabilitySens_MS_WD']  = ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'MS')] - ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'WD')]
                ProbabilityScoreSens_P3['ProbabilitySens_MS_NMS'] = ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'MS')] - ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreSens_N_MS = ",  ProbabilityScoreSens_P1)
                print("ProbabilityScoreSens_WD_MS= ", ProbabilityScoreSens_P2)
                print("ProbabilityScoreSens_NMS_MS = ", ProbabilityScoreSens_P3)

            # les paires de sous-groupes : SA_N (Sourd-Aveugle / Neutre), - SA_WD (Sourd-Aveugle / Without Disability: sans-handicap), SA_NMS (Sourd-Aveugle / Ni Sourd Ni Malentendant)
            case 'SA': # (Sourd-Aveugle)
                grN = 'SA_N'
                grWD = 'SA_WD'
                grNMS = 'SA_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreSens_P1 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreSens_P2 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreSens_P3 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreSens_P1['ProbabilitySens_SA_N']   = ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'SA')] - ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'N')]
                ProbabilityScoreSens_P2['ProbabilitySens_SA_WD']  = ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'SA')] - ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'WD')]
                ProbabilityScoreSens_P3['ProbabilitySens_SA_NMS'] = ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'SA')] - ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreSens_N_SA = ",   ProbabilityScoreSens_P1)
                print("ProbabilityScoreSens_WD_SA = ",  ProbabilityScoreSens_P2)
                print("ProbabilityScoreSens_NMS_SA = ", ProbabilityScoreSens_P3)

            # les paires de sous-groupes : SP_N (Sourd-Plus / Neutre), - SP_WD (Sourd-Plus / Without Disability: sans-handicap), SP_NMS (Sourd-Plus / Ni Sourd Ni Malentendant)
            case 'SP': # (Sourd-Plus)
                grN = 'SP_N'
                grWD = 'SP_WD'
                grNMS = 'SP_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreSens_P1 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreSens_P2 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreSens_P3 = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreSens_P1['ProbabilitySens_SP_N']   = ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'SP')] - ProbabilityScoreSens_P1[('mean', 'ProbabilityMean', 'N')]
                ProbabilityScoreSens_P2['ProbabilitySens_SP_WD']  = ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'SP')] - ProbabilityScoreSens_P2[('mean', 'ProbabilityMean', 'WD')]
                ProbabilityScoreSens_P3['ProbabilitySens_SP_NMS'] = ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'SP')] - ProbabilityScoreSens_P3[('mean', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreSens_N_SP = ",   ProbabilityScoreSens_P1)
                print("ProbabilityScoreSens_WD_SP = ",  ProbabilityScoreSens_P2)
                print("ProbabilityScoreSens_NMS_SP = ", ProbabilityScoreSens_P3)


            #case 'NS': # Non-Sourd - NON ENCORE TRAITÉ
            #case 'NM': # Non-Malentendant - NON ENCORE TRAITÉ

   return ProbabilityScoreSens_P1,ProbabilityScoreSens_P2,ProbabilityScoreSens_P3,grN,grWD,grNMS

# Analyse des scores de probabilités des etiquettes des emotions prédites par le modele
# -EmotionElectraClassifier pour le calcul de la metrique - ScoreSens introduite dans
# (Prabhakaran Vinodkumar et al., 2019).


# Parcourir la liste des fichiers -.csv (contenant les résultats des fusions des trois sequences)

file_paths_results = list(Path(AllFusionMasks_path).glob("*.csv"))
# par groupe : by = "G"

# par sous groupe :
by = "SG"
for file_result in file_paths_results:

    # Calcul de la métrique - ScoreSens (groupée par : -Connector+Mask+Label-CML / -Connector+Label-CL / -Mask+Label-ML / -Label-L)
    ProbabilityScoreSens_CML, ProbabilityScoreSens_CL, ProbabilityScoreSens_ML, ProbabilityScoreSens_L = calculProbabilityScoreSens(file_result, by)
    ProbabilityScoreSensP1_CML,ProbabilityScoreSensP2_CML,ProbabilityScoreSensP3_CML,gr1,gr2,gr3 = filterProbabilityScoreSens(ProbabilityScoreSens_CML)
    ProbabilityScoreSensP1_CL,ProbabilityScoreSensP2_CL,ProbabilityScoreSensP3_CL,gr1,gr2,gr3 = filterProbabilityScoreSens(ProbabilityScoreSens_CL)
    ProbabilityScoreSensP1_ML,ProbabilityScoreSensP2_ML,ProbabilityScoreSensP3_ML,gr1,gr2,gr3 = filterProbabilityScoreSens(ProbabilityScoreSens_ML)
    ProbabilityScoreSensP1_L,ProbabilityScoreSensP2_L,ProbabilityScoreSensP3_L,gr1,gr2,gr3 = filterProbabilityScoreSens(ProbabilityScoreSens_L)

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Transfert des résultats dans un fichier -.csv
      # by connector+mask+label
    outputFileNameCsvOfCML   = "metricScoreSens-by_ConnectorMaskLabel" + fileName + ".csv"
    ProbabilityScoreSens_CML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfCML, sep=";", index=False)
      # by connector+label
    outputFileNameCsvOfCL    = "metricScoreSens-by_ConnectorLabel"     + fileName + ".csv"
    ProbabilityScoreSens_CL.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfCL, sep=";", index=False)
      # by mask+label
    outputFileNameCsvOfML     = "metricScoreSens-by_MaskLabel"          + fileName + ".csv"
    ProbabilityScoreSens_ML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfML, sep=";", index=False)
    # by label
    outputFileNameCsvOfL     = "metricScoreSens-by_Label"          + fileName + ".csv"
    ProbabilityScoreSens_L.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfL, sep=";", index=False)

    # Transfert des résultats filtrés de chaque paire de sous-groupes dans un fichier -.csv

      # by connector+mask+label
    outputFileNameCsvOfP1_CML   = gr1 + "-by_ConnectorMaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP2_CML   = gr2 + "-by_ConnectorMaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP3_CML   = gr3 + "-by_ConnectorMaskLabel_" + fileName + ".csv"

    ProbabilityScoreSensP1_CML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP1_CML, sep=";", index=False)
    ProbabilityScoreSensP2_CML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP2_CML, sep=";", index=False)
    ProbabilityScoreSensP3_CML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP3_CML, sep=";", index=False)

    # by connector+label
    outputFileNameCsvOfP1_CL    = gr1 + "-by_ConnectorLabel_" + fileName + ".csv"
    outputFileNameCsvOfP2_CL    = gr2 + "-by_ConnectorLabel_" + fileName + ".csv"
    outputFileNameCsvOfP3_CL    = gr3 + "-by_ConnectorLabel_" + fileName + ".csv"

    ProbabilityScoreSensP1_CL.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP1_CL, sep=";", index=False)
    ProbabilityScoreSensP2_CL.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP2_CL, sep=";", index=False)
    ProbabilityScoreSensP3_CL.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP3_CL, sep=";", index=False)

    # by mask+label
    outputFileNameCsvOfP1_ML       = gr1 +  "-by_MaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP2_ML       = gr2 +  "-by_MaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP3_ML       = gr3 +  "-by_MaskLabel_" + fileName + ".csv"

    ProbabilityScoreSensP1_ML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP1_ML, sep=";", index=False)
    ProbabilityScoreSensP2_ML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP2_ML, sep=";", index=False)
    ProbabilityScoreSensP3_ML.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP3_ML, sep=";", index=False)

    # by label
    outputFileNameCsvOfP1_L       = gr1 +  "-by_Label_" + fileName + ".csv"
    outputFileNameCsvOfP2_L       = gr2 +  "-by_Label_" + fileName + ".csv"
    outputFileNameCsvOfP3_L       = gr3 +  "-by_Label_" + fileName + ".csv"

    ProbabilityScoreSensP1_L.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP1_L, sep=";", index=False)
    ProbabilityScoreSensP2_L.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP2_L, sep=";", index=False)
    ProbabilityScoreSensP3_L.to_csv(metric_ScoreSens_path  + outputFileNameCsvOfP3_L, sep=";", index=False)

    #outputFileNameExcel = "metricScoreSens-" + by + "_EmotionClassifier_" + fileName + ".xlsx"
    #ProbabilitySens.to_excel(metric_ScoreSens_path  + outputFileNameExcel, index=False)

# Fin de calcul de la metrique - ScoreSens pour -EmotionElectraClassifier.

# Définition d'une fonction qui calcule le score de sensibilité (la probabilité de prédiction
# de l'etiquette d'émotion) entre les différents groupes (ou sous-groupes) : la metrique - ScoreDev
# (l'ecart type) introduite dans (Prabhakaran Vinodkumar et al., 2019).

def calculProbabilityScoreDev(filePath,by):

    # Parcourir le fichier .csv (du dossier "AllFusionMaskFiles...") entré en parametre
    pdFusion = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # les scores moyens groupés par sous groupes
    if by == "SG" :
         #print("SG-pdFusion / par sous-groupes = ", pdFusion)

         # Création du tableau dynamique croisé / fonction d'aggrégation = l'ecart type des scores
         # de probabilité de prediction des étiquettes (ou labels) d'emotion

         # by connector + mask + label
         ProbabilityScoreDevRes_CML = pd.pivot_table(pdFusion,index=["connector", "mask", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.std], fill_value=0).reset_index()

         # by connector + label
         ProbabilityScoreDevRes_CL = pd.pivot_table(pdFusion,index=["connector", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.std], fill_value=0).reset_index()

         # by mask + label
         ProbabilityScoreDevRes_ML = pd.pivot_table(pdFusion,index=["mask", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.std], fill_value=0).reset_index()

         # by label
         ProbabilityScoreDevRes_L = pd.pivot_table(pdFusion,index=["label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc=[np.std], fill_value=0).reset_index()

    # les scores moyens groupés par groupes
    else :
         print("pdFusion / par groupes = ", pdFusion.columns)

         # Création du tableau dynamique croisé / fonction d'aggrégation = la moyenne des scores

         # by connector + mask + label
         ProbabilityScoreDevRes_CML = pd.pivot_table(pdFusion,index=["connector", "mask", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.std], fill_value=0).reset_index()
         # by connector + label
         ProbabilityScoreDevRes_CL = pd.pivot_table(pdFusion,index=["connector", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.std], fill_value=0).reset_index()
         # by mask + label
         ProbabilityScoreDevRes_ML = pd.pivot_table(pdFusion,index=["mask", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.std], fill_value=0).reset_index()
         # by label
         ProbabilityScoreDevRes_L = pd.pivot_table(pdFusion,index=["label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc=[np.std], fill_value=0).reset_index()

         #print("ProbabilityScoreDevRes_CML = ", ProbabilityScoreDevRes_CML.columns)

    return ProbabilityScoreDevRes_CML,ProbabilityScoreDevRes_CL,ProbabilityScoreDevRes_ML,ProbabilityScoreDevRes_L

# Définition d'une fonction qui filtre le résultat de la fonction - CalculScoreDev
# pour faciliter le calcul

def filterProbabilityScoreDev(pdFile):

   ProbabilityScoreDev_P1 = []
   ProbabilityScoreDev_P2 = []
   ProbabilityScoreDev_P3 = []
   #sgr = ''
   # Parcourir le fichier .csv entré en parametre
   pdFileToFilter = pdFile

   # parcourir la liste des noms des colonnes
   for m,s,g in pdFileToFilter.columns.values:
       match g:
            # les paires de sous-groupes - S_N (Sourd / Neutre) , - S_WD (Sourd / Without Disability), -S_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'S': # Sourd
                grN = 'S_N'
                grWD = 'S_WD'
                grNMS = 'S_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreDev_P1['ProbabilityScoreDev_S_N']   = ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'S')] - ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'N')]
                ProbabilityScoreDev_P2['ProbabilityScoreDev_S_WD']  = ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'S')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'WD')]
                ProbabilityScoreDev_P3['ProbabilityScoreDev_S_NMS'] = ProbabilityScoreDev_P3[('std', 'ProbabilityMean', 'S')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreDev_N_S = ",  ProbabilityScoreDev_P1)
                print("ProbabilityScoreDev_WD_S = ",  ProbabilityScoreDev_P2)
                print("ProbabilityScoreDev_NMS_S = ",  ProbabilityScoreDev_P3)


            # les paires de sous-groupes - M_N (Malentendant / Neutre) , - M_WD (Malentendant / Without Disability), -M_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'M':
                grN = 'M_N'
                grWD = 'M_WD'
                grNMS = 'M_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'N')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreDev_P1['ProbabilityScoreDev_MN']  = ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'M')] - ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'N')]
                ProbabilityScoreDev_P2['ProbabilityScoreDev_MWd'] = ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'M')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'WD')]
                ProbabilityScoreDev_P3['ProbabilityScoreDev_MWd'] = ProbabilityScoreDev_P3[('std', 'ProbabilityMean', 'M')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreDev_N_M = ",  ProbabilityScoreDev_P1)
                print("ProbabilityScoreDev_WD_M = ", ProbabilityScoreDev_P2)
                print("ProbabilityScoreDev_NMS_M = ", ProbabilityScoreDev_P3)

            # les paires de sous-groupes : MS_N (Sourd et/ou Malentendant / Neutre), - MS_WD (Sourd et/ou Malentendant / Without Disability: sans-handicap), MS_NMS (Sourd et/ou Malentendant / Ni Sourd Ni Malentendant)
            case 'MS': # (Sourd et/ou Malentendant)
                grN = 'MS_N'
                grWD = 'MS_WD'
                grNMS = 'MS_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreDev_P1['ProbabilityScoreDev_MS_N']   = ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'MS')] - ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'N')]
                ProbabilityScoreDev_P2['ProbabilityScoreDev_MS_WD']  = ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'MS')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'WD')]
                ProbabilityScoreDev_P3['ProbabilityScoreDev_MS_NMS'] = ProbabilityScoreDev_P3[('std', 'ProbabilityMean', 'MS')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreDev_N_MS = ",  ProbabilityScoreDev_P1)
                print("ProbabilityScoreDev_WD_MS = ",  ProbabilityScoreDev_P2)
                print("ProbabilityScoreDev_NMS_MS = ",  ProbabilityScoreDev_P3)

            # les paires de sous-groupes : SA_N (Sourd-Aveugle / Neutre), - SA_WD (Sourd-Aveugle / Without Disability: sans-handicap), SA_NMS (Sourd-Aveugle / Ni Sourd Ni Malentendant)
            case 'SA': # (Sourd-Aveugle)
                grN = 'SA_N'
                grWD = 'SA_WD'
                grNMS = 'SA_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreDev_P1['ProbabilityScoreDev_SA_N']   = ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'SA')] - ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'N')]
                ProbabilityScoreDev_P2['ProbabilityScoreDev_SA_WD']  = ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'SA')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'WD')]
                ProbabilityScoreDev_P3['ProbabilityScoreDev_SA_NMS'] = ProbabilityScoreDev_P3[('std', 'ProbabilityMean', 'SA')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreDev_N_SA = ",  ProbabilityScoreDev_P1)
                print("ProbabilityScoreDev_WD_SA = ",  ProbabilityScoreDev_P2)
                print("ProbabilityScoreDev_NMS_SA = ",  ProbabilityScoreDev_P3)

            # les paires de sous-groupes : SP_N (Sourd-Plus / Neutre), - SP_WD (Sourd-Plus / Without Disability: sans-handicap), SP_NMS (Sourd-Plus / Ni Sourd Ni Malentendant)
            case 'SP': # (Sourd-Plus)
                grN = 'SP_N'
                grWD = 'SP_WD'
                grNMS = 'SP_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreDev_P1  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('std', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreDev_P2  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreDev_P3  = pdFileToFilter.loc[(pdFileToFilter[('std', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('std', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreDev_P1['ProbabilityScoreDev_SP_N']   = ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'SP')] - ProbabilityScoreDev_P1[('std', 'ProbabilityMean', 'N')]
                ProbabilityScoreDev_P2['ProbabilityScoreDev_SP_WD']  = ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'SP')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'WD')]
                ProbabilityScoreDev_P3['ProbabilityScoreDev_SP_NMS'] = ProbabilityScoreDev_P3[('std', 'ProbabilityMean', 'SP')] - ProbabilityScoreDev_P2[('std', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreDev_N_SP = ",  ProbabilityScoreDev_P1)
                print("ProbabilityScoreDev_WD_SP= ",  ProbabilityScoreDev_P2)
                print("ProbabilityScoreDev_NMS_SP = ",  ProbabilityScoreDev_P3)

            #case 'NS': # Non-Sourd - NON ENCORE TRAITÉ
            #case 'NM': # Non-Malentendant - NON ENCORE TRAITÉ

   return ProbabilityScoreDev_P1,ProbabilityScoreDev_P2,ProbabilityScoreDev_P3,grN,grWD,grNMS

# Analyse des scores de probabilités des etiquettes d'emotion prédites par le modele
# -EmotionElectraClassifier pour le calcul de la metrique - ScoreDev (l'ecart type)
# introduite dans (Prabhakaran Vinodkumar et al., 2019).

# Parcourir la liste des fichiers -.csv (contenant les résultats des fusions des trois sequences)

file_paths_results = list(Path(AllFusionMasks_path).glob("*.csv"))
# par groupe : by = "G"

# par sous groupe :
by = "SG"
for file_result in file_paths_results:

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Calcul de la métrique - ScoreDev (groupée par : Connector+Mask+Label-CML / Connector+Label-CL / Mask+Label-ML / Label-L)
    ProbabilityScoreDev_CML, ProbabilityScoreDev_CL, ProbabilityScoreDev_ML, ProbabilityScoreDev_L = calculProbabilityScoreDev(file_result, by)

    # Transfert des résultats dans un fichier -.csv
      # by connector+mask+label
    outputFileNameCsvOfCML   = "metricScoreDev-by_ConnectorMaskLabel" + fileName + ".csv"
    ProbabilityScoreDev_CML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfCML, sep=";", index=False)
      # by connector+label
    outputFileNameCsvOfCL   = "metricScoreDev-by_ConnectorLabel" + fileName + ".csv"
    ProbabilityScoreDev_CL.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfCL, sep=";", index=False)
      # by mask+label
    outputFileNameCsvOfML    = "metricScoreDev-by_MaskLabel" + fileName + ".csv"
    ProbabilityScoreDev_ML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfML, sep=";", index=False)
    # by label
    outputFileNameCsvOfL    = "metricScoreDev-by_Label" + fileName + ".csv"
    ProbabilityScoreDev_L.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfL, sep=";", index=False)

    # Transfert des résultats filtrés de chaque paire de sous-groupes dans un fichier -.csv

      # Groupés par connector+mask+label
    if (ProbabilityScoreDev_CML.size != 0 ):

       ProbabilityScoreDevP1_CML,ProbabilityScoreDevP2_CML,ProbabilityScoreDevP3_CML,gr1,gr2,gr3 = filterProbabilityScoreDev(ProbabilityScoreDev_CML)

       outputFileNameCsvOfP1_CML   = gr1 + "-by_ConnectorMaskLabel_" + fileName + ".csv"
       outputFileNameCsvOfP2_CML   = gr2 + "-by_ConnectorMaskLabel_"  + fileName + ".csv"
       outputFileNameCsvOfP3_CML   = gr3 + "-by_ConnectorMaskLabel_"  + fileName + ".csv"

       ProbabilityScoreDevP1_CML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP1_CML, sep=";", index=False)
       ProbabilityScoreDevP2_CML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP2_CML, sep=";", index=False)
       ProbabilityScoreDevP3_CML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP3_CML, sep=";", index=False)

      # Groupés par connector+label

    if (ProbabilityScoreDev_CL.size != 0 ):

      ProbabilityScoreDevP1_CL,ProbabilityScoreDevP2_CL,ProbabilityScoreDevP3_CL,gr1,gr2,gr3 = filterProbabilityScoreDev(ProbabilityScoreDev_CL)

      outputFileNameCsvOfP1_CL   = gr1 + "-by_ConnectorLabel_" + fileName + ".csv"
      outputFileNameCsvOfP2_CL   = gr2 + "-by_ConnectorLabel_"  + fileName + ".csv"
      outputFileNameCsvOfP3_CL   = gr3 + "-by_ConnectorLabel_"  + fileName + ".csv"

      ProbabilityScoreDevP1_CL.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP1_CL, sep=";", index=False)
      ProbabilityScoreDevP2_CL.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP2_CL, sep=";", index=False)
      ProbabilityScoreDevP3_CL.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP3_CL, sep=";", index=False)

      # Groupés par mask+label

    if (ProbabilityScoreDev_ML.size != 0 ):

      ProbabilityScoreDevP1_ML,ProbabilityScoreDevP2_ML,ProbabilityScoreDevP3_ML,gr1,gr2,gr3 = filterProbabilityScoreDev(ProbabilityScoreDev_ML)

      outputFileNameCsvOfP1_ML   = gr1 + "-by_MaskLabel_" + fileName + ".csv"
      outputFileNameCsvOfP2_ML   = gr2 + "-by_MaskLabel_"  + fileName + ".csv"
      outputFileNameCsvOfP3_ML   = gr3 + "-by_MaskLabel_"  + fileName + ".csv"

      ProbabilityScoreDevP1_ML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP1_ML, sep=";", index=False)
      ProbabilityScoreDevP2_ML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP2_ML, sep=";", index=False)
      ProbabilityScoreDevP3_ML.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP3_ML, sep=";", index=False)

      # Groupés par  label

    if (ProbabilityScoreDev_L.size != 0 ):

      ProbabilityScoreDevP1_L,ProbabilityScoreDevP2_L,ProbabilityScoreDevP3_L,gr1,gr2,gr3 = filterProbabilityScoreDev(ProbabilityScoreDev_L)

      outputFileNameCsvOfP1_L   = gr1 + "-by_Label_" + fileName + ".csv"
      outputFileNameCsvOfP2_L   = gr2 + "-by_Label_"  + fileName + ".csv"
      outputFileNameCsvOfP3_L   = gr3 + "-by_Label_"  + fileName + ".csv"

      ProbabilityScoreDevP1_L.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP1_L, sep=";", index=False)
      ProbabilityScoreDevP2_L.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP2_L, sep=";", index=False)
      ProbabilityScoreDevP3_L.to_csv(metric_ScoreDev_path  + outputFileNameCsvOfP3_L, sep=";", index=False)

    #outputFileNameExcel = "metricScoreDev-" + by + "_EmotionClassifier_" + fileName + ".xlsx"
    #ProbabilitySens.to_excel(metric_ScoreDev_path  + outputFileNameExcel, index=False)

# Fin de calcul de la metrique - ScoreDev pour -EmotionElectraClassifier.

# Analyse des scores de probabilités des etiquettes d'emotion prédites par le modele
# -EmotionElectraClassifier pour le calcul de la metrique - ScoreRange (Max-Min) introduite
# dans (Prabhakaran Vinodkumar et al., 2019).

def calculProbabilityScoreRange(filePath,by):

    # Parcourir le fichier .csv (du dossier "AllFusionMaskFiles...") entré en parametre
    pdFusion = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # les scores moyens groupés par sous groupes
    if by == "SG" :
         #print("SG-pdFusion / par sous-groupes = ", pdFusion)

         # Création du tableau dynamique croisé / fonction d'aggrégation = ProbabilityMean (Min-Max)
         # des scores de probabilité de prediction des étiquettes (ou labels) d'emotion

         # by connector + mask + label
         ProbabilityScoreRangeRes_CML = pd.pivot_table(pdFusion,index=["connector", "mask", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
         # by connector + label
         ProbabilityScoreRangeRes_CL = pd.pivot_table(pdFusion,index=["connector", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
         # by mask + label
         ProbabilityScoreRangeRes_ML = pd.pivot_table(pdFusion,index=["mask", "label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
         # by label
         ProbabilityScoreRangeRes_L = pd.pivot_table(pdFusion,index=["label"], values=["ProbabilityMean"], columns=["sousGroupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()

    # les scores moyens groupés par groupes
    else :
         print("pdFusion / par groupes = ", pdFusion.columns)

         # Création du tableau dynamique croisé / fonction d'aggrégation = ProbabilityMean (Min-Max)

         # by connector + mask + label
         ProbabilityScoreRangeRes_CML = pd.pivot_table(pdFusion,index=["connector", "mask", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
         # by connector + label
         ProbabilityScoreRangeRes_CL = pd.pivot_table(pdFusion,index=["connector", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
         # by mask + label
         ProbabilityScoreRangeRes_ML = pd.pivot_table(pdFusion,index=["mask", "label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()
         # by label
         ProbabilityScoreRangeRes_L = pd.pivot_table(pdFusion,index=["label"], values=["ProbabilityMean"], columns=["groupe"], aggfunc= [np.min,np.max], fill_value=0).reset_index()

         #print("ProbabilityScoreRangeRes = ", ProbabilityScoreRangeRes.columns)

    return ProbabilityScoreRangeRes_CML,ProbabilityScoreRangeRes_CL,ProbabilityScoreRangeRes_ML,ProbabilityScoreRangeRes_L

# Définition d'une fonction qui filtre le résultat de la fonction - CalculScoreRange (Max-Min)
# pour faciliter le calcul

def filterProbabilityScoreRange(pdFile):

   ProbabilityScoreRange_P1 = []
   ProbabilityScoreRange_P2 = []
   ProbabilityScoreRange_P3 = []
   #sgr = ''
   # Parcourir le fichier .csv entré en parametre
   pdFileToFilter = pdFile

   # parcourir la liste des noms des colonnes
   for m,s,g in pdFileToFilter.columns.values:
       match g:
            # les paires de sous-groupes - S_N (Sourd / Neutre) , - S_WD (Sourd / Without Disability), -S_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'S':
                grN = 'S_N'
                grWD = 'S_WD'
                grNMS = 'S_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('min', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('max', 'ProbabilityMean', 'S')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'S')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'S')] != 0)]
                ProbabilityScoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'S')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'S')] != 0)]
                # Agrégat = Max
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMax_S_N']   = ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'S')] - ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMax_S_WD']  = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'S')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMax_S_NMS'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'S')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'NMS')]
                # Agrégat = Min
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMin_S_N']   = ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'S')] - ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMin_S_WD']  = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'S')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMin_S_NMS'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'S')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreRange_N_S = ",  ProbabilityScoreRange_P1)
                print("ProbabilityScoreRange_WD_S = ", ProbabilityScoreRange_P2)
                print("ProbabilityScoreRange_NMS_S = ", ProbabilityScoreRange_P3)

            # les paires de sous-groupes - M_N (Malentendant / Neutre) , - M_WD (Malentendant / Without Disability), -M_NMS (Sourd / Ni Sourd Ni Malentendant)
            case 'M':
                grN = 'M_N'
                grWD = 'M_WD'
                grNMS = 'M_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('min', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('max', 'ProbabilityMean', 'M')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'M')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'M')] != 0)]
                ProbabilityScoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'M')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'M')] != 0)]
                # Agrégat = Max
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMax_M_N']  = ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'M')] - ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMax_M_WD'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'M')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMax_M_NMS'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'M')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'NMS')]
                # Agrégat = Min
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMin_M_N']  = ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'M')] - ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMin_M_WD'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'M')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMin_M_NMS'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'M')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreRange_N_M = ",  ProbabilityScoreRange_P1)
                print("ProbabilityScoreRange_WD_M = ", ProbabilityScoreRange_P2)
                print("ProbabilityScoreRange_NMS_M = ", ProbabilityScoreRange_P3)

            # les paires de sous-groupes : MS_N (Sourd et/ou Malentendant / Neutre), - MS_WD (Sourd et/ou Malentendant / Without Disability: sans-handicap), MS_NMS (Sourd et/ou Malentendant / Ni Sourd Ni Malentendant)
            case 'MS': # (Sourd et/ou Malentendant)
                grN = 'MS_N'
                grWD = 'MS_WD'
                grNMS = 'MS_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('min', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('max', 'ProbabilityMean', 'MS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'MS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'MS')] != 0)]
                ProbabilityScoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'MS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'MS')] != 0)]
                # Agrégat = Max
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMax_MS_N']  = ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'MS')] - ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMax_MS_WD'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'MS')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMax_MS_NMS'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'MS')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'NMS')]
                # Agrégat = Min
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMin_MS_N']  = ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'MS')] - ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMin_MS_WD'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'MS')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMin_MS_NMS'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'MS')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreRange_N_MS = ",  ProbabilityScoreRange_P1)
                print("ProbabilityScoreRange_WD_MS = ", ProbabilityScoreRange_P2)
                print("ProbabilityScoreRange_NMS_MS = ", ProbabilityScoreRange_P3)

            # les paires de sous-groupes : SA_N (Sourd-Aveugle / Neutre), - SA_WD (Sourd-Aveugle / Without Disability: sans-handicap), SA_NMS (Sourd-Aveugle / Ni Sourd Ni Malentendant)
            case 'SA': # (Sourd-Aveugle)
                grN = 'SA_N'
                grWD = 'SA_WD'
                grNMS = 'SA_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('min', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('max', 'ProbabilityMean', 'SA')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'SA')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'SA')] != 0)]
                ProbabilityScoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'SA')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'SA')] != 0)]
                # Agrégat = Max
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMax_SA_N']  = ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'SA')] - ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMax_SA_WD'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'SA')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMax_SA_NMS'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'SA')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'NMS')]
                # Agrégat = Min
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMin_SA_N']  = ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'SA')] - ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMin_SA_WD'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'SA')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMin_SA_NMS'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'SA')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreRange_N_SA = ",  ProbabilityScoreRange_P1)
                print("ProbabilityScoreRange_WD_SA = ", ProbabilityScoreRange_P2)
                print("ProbabilityScoreRange_NMS_SA = ", ProbabilityScoreRange_P3)



            # les paires de sous-groupes : SP_N (Sourd-Plus / Neutre), - SP_WD (Sourd-Plus / Without Disability: sans-handicap), SP_NMS (Sourd-Plus / Ni Sourd Ni Malentendant)
            case 'SP': # (Sourd-Plus)
                grN = 'SP_N'
                grWD = 'SP_WD'
                grNMS = 'SP_NMS'

                # Filtrer les scores != 0 pour les sous groupes par paire
                ProbabilityScoreRange_P1  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('min', 'ProbabilityMean', 'N')] != 0)  & (pdFileToFilter[('max', 'ProbabilityMean', 'SP')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreRange_P2  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'WD')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'SP')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'SP')] != 0)]
                ProbabilityScoreRange_P3  = pdFileToFilter.loc[(pdFileToFilter[('max', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'NMS')] != 0) & (pdFileToFilter[('max', 'ProbabilityMean', 'SP')] != 0) & (pdFileToFilter[('min', 'ProbabilityMean', 'SP')] != 0)]
                # Agrégat = Max
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMax_SP_N']  = ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'SP')] - ProbabilityScoreRange_P1[('max', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMax_SP_WD'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'SP')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMax_SP_NMS'] = ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'SP')] - ProbabilityScoreRange_P2[('max', 'ProbabilityMean', 'NMS')]
                # Agrégat = Min
                ProbabilityScoreRange_P1['ProbabilityScoreRangeMin_SP_N']  = ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'SP')] - ProbabilityScoreRange_P1[('min', 'ProbabilityMean', 'N')]
                ProbabilityScoreRange_P2['ProbabilityScoreRangeMin_SP_WD'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'SP')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'WD')]
                ProbabilityScoreRange_P3['ProbabilityScoreRangeMin_SP_NMS'] = ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'SP')] - ProbabilityScoreRange_P2[('min', 'ProbabilityMean', 'NMS')]

                print("ProbabilityScoreRange_N_SP = ",  ProbabilityScoreRange_P1)
                print("ProbabilityScoreRange_WD_SP = ", ProbabilityScoreRange_P2)
                print("ProbabilityScoreRange_NMS_SP = ", ProbabilityScoreRange_P3)


            #case 'NS':  # Non-Sourd - NON ENCORE TRAITÉ
            #case 'NM':  # Non-Malentendant - NON ENCORE TRAITÉ

   return ProbabilityScoreRange_P1,ProbabilityScoreRange_P2,ProbabilityScoreRange_P3,grN,grWD,grNMS

# Analyse des scores de probabilités des etiquettes d'emotion prédites par le modele
# -EmotionElectraClassifier pour le calcul de la metrique - - ScoreRange (Max-Min) introduite
# dans (Prabhakaran Vinodkumar et al., 2019).

# Parcourir la liste des fichiers -.csv (contenant les résultats des fusions des trois sequences)

file_paths_results = list(Path(AllFusionMasks_path).glob("*.csv"))
# par groupe : by = "G"

# par sous groupe :
by = "SG"
for file_result in file_paths_results:

    # Calcul de la métrique - ScoreSens (groupée par : Connector+Mask+Label-CML / Connector+Label-CL / Mask+Label-ML)
    ProbabilityScoreRange_CML,ProbabilityScoreRange_CL,ProbabilityScoreRange_ML,ProbabilityScoreRange_L  = calculProbabilityScoreRange(file_result, by)
    ProbabilityScoreRangeP1_CML,ProbabilityScoreRangeP2_CML,ProbabilityScoreRangeP3_CML,gr1,gr2,gr3 = filterProbabilityScoreRange(ProbabilityScoreRange_CML)
    ProbabilityScoreRangeP1_CL,ProbabilityScoreRangeP2_CL,ProbabilityScoreRangeP3_CL,gr1,gr2,gr3 = filterProbabilityScoreRange(ProbabilityScoreRange_CL)
    ProbabilityScoreRangeP1_ML,ProbabilityScoreRangeP2_ML,ProbabilityScoreRangeP3_ML,gr1,gr2,gr3 = filterProbabilityScoreRange(ProbabilityScoreRange_ML)
    ProbabilityScoreRangeP1_L,ProbabilityScoreRangeP2_L,ProbabilityScoreRangeP3_L,gr1,gr2,gr3 = filterProbabilityScoreRange(ProbabilityScoreRange_L)
    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Transfert des résultats dans un fichier -.csv

      # by connector+mask+label
    outputFileNameCsvOfCML   = "metricScoreRange-by_ConnectorMaskLabel" + fileName + ".csv"
    ProbabilityScoreRange_CML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfCML, sep=";", index=False)
      # by connector+label
    outputFileNameCsvOfCL   = "metricScoreRange-by_ConnectorLabel" + fileName + ".csv"
    ProbabilityScoreRange_CL.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfCL, sep=";", index=False)
      # by mask+label
    outputFileNameCsvOfML   = "metricScoreRange-by_MaskLabel" + fileName + ".csv"
    ProbabilityScoreRange_ML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfML, sep=";", index=False)
    # by label
    outputFileNameCsvOfL   = "metricScoreRange-by_Label" + fileName + ".csv"
    ProbabilityScoreRange_L.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfL, sep=";", index=False)

    # Transfert des résultats filtrés de chaque paire de sous-groupes dans un fichier -.csv

      # by connector+mask+label
    outputFileNameCsvOfP1_CML   = gr1 + "-by_ConnectorMaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP2_CML   = gr2 + "-by_ConnectorMaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP3_CML   = gr3 + "-by_ConnectorMaskLabel_" + fileName + ".csv"
    ProbabilityScoreRangeP1_CML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP1_CML, sep=";", index=False)
    ProbabilityScoreRangeP2_CML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP2_CML, sep=";", index=False)
    ProbabilityScoreRangeP3_CML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP3_CML, sep=";", index=False)

      # by connector+label
    outputFileNameCsvOfP1_CL   = gr1 + "-by_ConnectorLabel_" + fileName + ".csv"
    outputFileNameCsvOfP2_CL   = gr2 + "-by_ConnectorLabel_" + fileName + ".csv"
    outputFileNameCsvOfP3_CL   = gr3 + "-by_ConnectorLabel_" + fileName + ".csv"
    ProbabilityScoreRangeP1_CL.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP1_CL, sep=";", index=False)
    ProbabilityScoreRangeP2_CL.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP2_CL, sep=";", index=False)
    ProbabilityScoreRangeP3_CL.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP3_CL, sep=";", index=False)

      # by mask+label
    outputFileNameCsvOfP1_ML   = gr1 + "-by_MaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP2_ML   = gr2 + "-by_MaskLabel_" + fileName + ".csv"
    outputFileNameCsvOfP3_ML   = gr3 + "-by_MaskLabel_" + fileName + ".csv"
    ProbabilityScoreRangeP1_ML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP1_ML, sep=";", index=False)
    ProbabilityScoreRangeP2_ML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP2_ML, sep=";", index=False)
    ProbabilityScoreRangeP3_ML.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP3_ML, sep=";", index=False)

    # by label
    outputFileNameCsvOfP1_L   = gr1 + "-by_Label_" + fileName + ".csv"
    outputFileNameCsvOfP2_L   = gr2 + "-by_Label_" + fileName + ".csv"
    outputFileNameCsvOfP3_L   = gr3 + "-by_Label_" + fileName + ".csv"
    ProbabilityScoreRangeP1_L.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP1_L, sep=";", index=False)
    ProbabilityScoreRangeP2_L.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP2_L, sep=";", index=False)
    ProbabilityScoreRangeP3_L.to_csv(metric_ScoreRange_path  + outputFileNameCsvOfP3_L, sep=";", index=False)


    #outputFileNameExcel = "metricScoreRange-" + by + "_EmotionClassifier_" + fileName + ".xlsx"
    #ProbabilitySens.to_excel(metric_ScoreRange_path  + outputFileNameExcel, index=False)

# Fin de calcul de la metrique - ScoreRange pour -EmotionElectraClassifier.

# Début de la partie du code: -Fusion des Masks / fichiers .csv

# Définition d'une fonction qui fusionne les trois masks / prompts remplis prédits par le Mlm-Electra-Large
# en faisant la moyenne des scores de probabilté des etiquettes regroupés par la valeur du score
# et puis retourne le résultat dans un objet Dataframe

def fusionMaksSeqs(filePath):

    # Parcourir le fichier .csv entré en parametre
    emoPredPd = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # extraire toutes les colonnes et les trois sequences / labels et leurs probabilités de prédiction séparemment
    fSequence1 = emoPredPd[['groupe', 'sousGroupe', 'connector' , 'spaceHolder', 'categorie', 'reference', 'mask1', 'label1', 'probability1', 'sequence1']]
    fSequence2 = emoPredPd[['groupe', 'sousGroupe', 'connector' , 'spaceHolder', 'categorie', 'reference', 'mask2', 'label2', 'probability2', 'sequence2',]]
    fSequence3 = emoPredPd[['groupe', 'sousGroupe', 'connector' , 'spaceHolder', 'categorie', 'reference', 'mask3', 'label3', 'probability3', 'sequence3']]

    # renommer les colonnes
    fSequence1 = fSequence1.rename(columns={"mask1": "mask", "label1": "label", "probability1": "probability", "sequence1": "sequence" })
    fSequence2 = fSequence2.rename(columns={"mask2": "mask", "label2": "label", "probability2": "probability", "sequence2": "sequence" })
    fSequence3 = fSequence3.rename(columns={"mask3": "mask", "label3": "label", "probability3": "probability", "sequence3": "sequence" })

    # fusionner les trois dataframes précedents
    frames = [fSequence1, fSequence2, fSequence3]
    fusionRes = pd.concat(frames)
    # print(fusionRes)

    # Group by : référence, connecteur, groupe, sous-groupe , mask et label
    by = "SG"
    pdTemp = fusionRes.groupby(['reference', 'connector', 'groupe', 'sousGroupe', 'mask', 'label'])['probability'].mean().reset_index(name='ProbabilityMean')

    # Group by : référence, connecteur, groupe, mask et label
    # by = "G"
    # pdTemp = fusionRes.groupby(['reference', 'connector', 'groupe', 'mask', 'label'])['probability'].mean().reset_index(name='ProbabilityMean')


    return pdTemp,by

# Fusion des trois masks / prompts remplis prédits par le MLM-Electra-Large
# et enregistrement des résultats dans des fichiers -.csv et -.xslx

# Parcourir la liste des fichiers -.csv (les prédiction du score des etiquettes d'emotion)
file_paths_results = list(Path(scoresEmotionElectra_path).glob("*.csv"))

for file_result in file_paths_results:

    fusionRes,by  = fusionMaksSeqs(file_result)

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Transfert des résultats dans un fichier -.csv
    #outputFileNameCsv   = "fusionProbabilityMean-"+ by  + fileName + ".csv"
    #fusionRes.to_csv(fusionMasks_path + outputFileNameCsv, sep=";", index=False)

    #outputFileNameExcel = "fusionProbabilityMean-"+ by + fileName + ".xlsx"

    # Transfert des résultats dans un fichier -.excel
    #outputFileNameExcel = "fusionProbabilityMean-"+ by + fileName + ".xlsx"
    #fusionRes.to_excel(fusionMasks_path + outputFileNameExcel, index=False)

# Fusion des fichiers -.csv du repertoire -fusionMasks (de chaque groupe & sous groupe)
# dans un même fichier -.csv (tous les groupes & sous groupes)

# Parcourir la liste des fichiers -.csv du repertoire -fusionSeq
file_paths_fusions = list(Path(fusionMasks_path).glob("*.csv"))
pdPred = pd.Series()

# fusionner les dataframes (de chaque groupe & sous groupe)
for file_fusion in file_paths_fusions:

    pdFusionFile = pd.read_csv(file_fusion,sep=";", skipinitialspace=True)

    if pdPred.empty : frames = [pdFusionFile]
    else : frames = [pdPred,pdFusionFile]

    fusionRes = pd.concat(frames)
    pdPred = fusionRes

# Transfert des résultats dans un fichier -csv
#outputFileNameCsv = "AllFusionMaskFiles_M_NMS_N_WD" + "_EmotionClassifier" + ".csv"
#outputFileNameCsv   = "AllFusionMaskFiles_S_NMS_N_WD" + "_EmotionClassifier" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_MS_NMS_N_WD" + "_EmotionClassifier" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_SA_NMS_N_WD" + "_EmotionClassifier" + ".csv"
#outputFileNameCsv = "AllFusionMaskFiles_SP_NMS_N_WD" + "_EmotionClassifier" + ".csv"

#pdPred.to_csv(AllFusionMasks_path  + outputFileNameCsv, sep=";", index=False)

# Fin de la partie du code: -Fusion des Masks / fichiers .csv