# -*- coding: utf-8 -*-
"""LabDistMetricEmotionClassifier_01Juin2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvlZPXCzR1ToQTLs9K7dXkgjYzzaus6u
"""

# Le programme de détection du biais de handicap dans le classificateur de textes (EmotionClassifier)
# Analyse des scores de probabilités des etiquettes d'EmotionClassifier :
# calcul de la metrique LabDist introduite dans (Prabhakaran Vinodkumar et al., 2019)
# Dernière modification: 21 Fevrier 2025

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

#scoresEmotionElectra_path = '/content/drive/MyDrive/scoresEmotionClassifier/'
#metric_ScoreSens_path  = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/ScoreSensEmotionClassifier/'

metric_ScoreSens_path  = '/content/drive/MyDrive/ToDo/'
metric_LabDist_path    = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/LabDistEmotionClassifier/LabDist-90/'
#metric_LabDist_path    = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/LabDistEmotionClassifier/LabDist-70/'
#metric_LabDist_path    = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/LabDistEmotionClassifier/LabDist-50/'

import pandas as pd
import numpy as np
#import math
from matplotlib import pyplot as plt
from pathlib import Path
import torch

# import seaborn as sns
# from tqdm.auto import tqdm
# tqdm.pandas()

# emotion_categories = ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# torch.device("cuda:0")
# device = torch.device("cuda")

# Définition d'une fonction qui calcule la distance de Jaccard sur les probabilités de prédiction
# (des étiquettes d'émotion) du classificateur de textes - EmotionClassifier.

def calculDistJaccard(filePath,threshold,gH,gC):

    # lecture du fichier .csv (du dossier "scoresEmotionClassifier...") entré en parametre
    pdScoresEmotion = pd.read_csv(filePath,sep=";", skipinitialspace=True)
    pdLabDist = pdScoresEmotion[2:]

    # Convertir en numerique les colonnes
    #pdLabDist = pdLabDist.astype({'mean': float, 'mean.1': float, 'mean.2': float, 'mean.3': float})

   # Enlever les etiquettes d'émotion en double de la colonne -Label
    pdLabels = pdLabDist['label'].drop_duplicates()
    print('pdLabels= ', pdLabels)

    # Classification binaire (0 ou 1) : la correspondance des probabilités de prédiction des
    # etiquettes en fonction du seuil de classification - threshold

    print('gH= ', gH, 'gC= ', gC)

    #print('pdLabDist debut = ', pdLabDist)
    #print('Seuil de Calssification= ', threshold)


    # groupes de handicap: -M, -MS (-Malentendant, -Malentendants et/ou Sourd)
    if (gH == 'M' or gH == 'MS'):

          pdLabDist['gHlabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean']) >= threshold else 0, axis = 1)

          match gC: # groupe de controle: -N, -NMS, -WD (-Neutre, -Malentendants et/ou Sourd, -non-handicap)

                # -N (Neutre)
                case 'N':
                    pdLabDist['gClabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean.1']) >= threshold else 0, axis = 1)

                # -WD (Without Disability -sans handicap)
                case 'WD':
                    pdLabDist['gClabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean.3']) >= threshold else 0, axis = 1)

                # -NSM (Ni Sourds-Ni Malentendants (personnes entendantes)
                case 'NMS':
                    pdLabDist['gClabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean.2']) >= threshold else 0, axis = 1)

          print('pdLabDist  = ', pdLabDist)

    # groupes de handicap -S, -SA, -SP : (-Sourd, -Sourd_Aveugle, -Sourd_Plus)
    elif (gH == 'S' or gH == 'SA' or gH == 'SP'):

          pdLabDist['gHlabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean.2']) >= threshold else 0, axis = 1)

          match gC: # groupe de controle: -N, -NMS, -WD (-Neutre, -Malentendants et/ou Sourd, -non-handicap)

              # -N (Neutre)
              case 'N':
                   pdLabDist['gClabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean']) >= threshold else 0, axis = 1)

              # -WD (Without Disability -sans handicap)
              case 'WD':
                   pdLabDist['gClabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean.3']) >= threshold else 0, axis = 1)

              # -NSM (Ni Sourds-Ni Malentendants (personnes entendantes)
              case 'NMS':
                 pdLabDist['gClabelClass'] = pdLabDist.apply(lambda x: 1 if float(x['mean.1']) >= threshold else 0, axis = 1)

    # Trier par ordre croissant des etiquettes d'émotion
    #pdLabDist = pdLabDist.sort_values(by = ['label','connector','mask'])
    #print('pdLabDist Trié = ', pdLabDist)

    # Calcul de la distance de Jaccard : distJaccard(A,B)
    pdDj=[]
    for label in pdLabels.values:
        pdLabel = pdLabDist.loc[pdLabDist['label'] == label]
        grH = pdLabel['gHlabelClass']
        grC = pdLabel['gClabelClass']
        pdDj.append(DistJaccard(grH.values,grC.values))

    # recuperer les résultats dans un Dataframe
    col1Name = 'label_' + gH + '_' + gC + '_' + str(threshold)
    pdLabDistJaccard =  pd.DataFrame(columns = [col1Name, 'dJaccard'])
    pdLabDistJaccard[col1Name] = pdLabels.values
    pdLabDistJaccard['dJaccard'] = pdDj

    return pdLabDistJaccard, pdLabDist

# la fonction de calcul de la distance de Jaccard

def DistJaccard(A,B):

  print('pdLabDist Trié A= ', A)
  print('pdLabDist Trié B= ', B)

  # Calcul de l'indice de Jaccard

  M11 = 0
  M00 = 0
  N = len(A)
  indJaccard = 0
  print('pdLabDist taille A= ', N)
  for i in range(N):
        # cacul du nombre de 1 dans A et B
    if (A[i]== 1 and B[i]== 1) : M11+=1
        # cacul du nombre de 0 dans A et B
    elif (A[i]== 0 and B[i]== 0) : M00+=1

  # Indice de Jaccard
  if (len(A) != M00) : indJaccard = M11/(len(A)-M00)
  # Distance de Jaccard
  JaccardDist = 1 - indJaccard

  return JaccardDist

# Analyse des scores de probabilités des etiquettes des emotions prédites par le modele
# -EmotionElectraClassifier pour le calcul de la metrique - LabDist introduite dans
# (Prabhakaran Vinodkumar et al., 2019).

# Parcourir la liste des fichiers -.csv (contenant les résultats des fusions des trois sequences)

file_paths_results = list(Path(metric_ScoreSens_path).glob("*.csv"))
# par groupe : by = "G"

# par sous groupe :
by = "SG"
#threshold = 50
#threshold = 70
threshold = 90
for file_result in file_paths_results:

  # extraire le nom du fichier sans l'extention
  fileName,ext = file_result.name.split(sep=".")

  # Extraite les codes des deux sous-groupes a traiter
  sgr = fileName[0:7]
  mgr = fileName[0:6]
  print("sgr = ",sgr)
  if (mgr != "metric"):
    sgHC,sep = sgr.split("-")
    sgH,sgC  = sgHC.split("_")

    print("H,C,sep = ",sgH,sgC,sep)

    LabDistJaccard, LabDistMetric  = calculDistJaccard(file_result,threshold,sgH,sgC)

    # Transfert des résultats dans un fichier -.csv
    outputFileNameCsv   = sgH + "_" + sgC + "_JaccardDist-" + str(threshold) + "_EmotionClassifier_" + ".csv"
    LabDistJaccard.to_csv(metric_LabDist_path  + outputFileNameCsv, sep=";", index=False)

    LabDistMetric.to_csv(metric_LabDist_path  + "MetricLabDist_"+ sgH + "_" + sgC + "_" + str(threshold) + "_EmotionClassifier_"+".csv", sep=";", index=False)

    #outputFileNameExcel = sgH + "_" + sgC + "_MetricLabDist-" + "_EmotionClassifier_" + fileName + ".xlsx"
    #LabDist.to_excel(metric_LabDist_path  + outputFileNameExcel, index=False)

# Fin de calcul de la mérique - LabDist