# -*- coding: utf-8 -*-
"""NormalityTestOfScores_01Juin2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vavpOFD5XVblr1h2keR2uNEBerTziST
"""

# Programme du test de Normalité de Shapiro-Wilk :
# https://openclassrooms.com/fr/courses/8313631-explorez-les-tests-statistiques/8497034-testez-la-normalite-des-donnees
# Dernière modification: 22 Avril 2025

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
#import numpy as np
#import math
#from matplotlib import pyplot as plt
from pathlib import Path
from scipy import stats
from scipy.stats import shapiro

scores_path_MlmElectra  = '/content/drive/MyDrive/ToDo_MLM/'
# scores_path_MlmElectra  = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsElectraGenerator/ScoreSensElectraGenerator/'

#scores_path_EmotionClassifier =  '/content/drive/MyDrive/ToDo/'
# scores_path_EmotionClassifier =  '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsEmotionClassifier/ScoreSensEmotionClassifier/'

#test_t_path_MlmElectra           = '/content/drive/MyDrive/metrics/TestDeStudent/Test_t_MLM-ELECTRA/'
norm_test_path_MlmElectra        = '/content/drive/MyDrive/metrics/Norm_test/Norm_test_MlmElectra/'
#norm_test_path_EmotionClassifier  = '/content/drive/MyDrive/metrics/Norm_test/Norm_test_EmotionClassifier/'
#test_t_path_EmotionClassifier     = '/content/drive/MyDrive/metrics/TestDeStudent/Test_t_EmotionClassifier/'

#scoreSens_P1  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'N')] != 0)  & (pdFileToFilter[('mean', 'ScoreMean', 'S')] != 0)]
                #scoreSens_P2  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'WD')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'S')] != 0)]
                #scoreSens_P3  = pdFileToFilter.loc[(pdFileToFilter[('mean', 'ScoreMean', 'NMS')] != 0) & (pdFileToFilter[('mean', 'ScoreMean', 'S')] != 0)]

# Définition de la fonction d'extraction des scores d'EmotionClassifier
def extractScoresEC(filePath,gH,gC):

    # parcourir le fichier .csv
    pdScores = pd.read_csv(filePath,sep=";", skipinitialspace=True)
    pdScoresHC = pdScores[2:]

    # Extraire les scores des groupes de Handicap (M,MS,S,SA,SP), de Controle (N,NMS) ou de non-handicap (WD)
    pdScoresH = []
    pdScoresC = []

    if (gH == 'M' or gH == 'MS'):

      pdScoresH = pdScoresHC['mean']
      match gC: # groupe de controle: -N, -NMS, -WD (-Neutre, -Malentendants et/ou Sourd, -non-handicap)

            # -N (Neutre)
            case 'N':
                pdScoresC = pdScoresHC['mean.1']

            # -NSM (Ni Sourds-Ni Malentendants (personnes entendantes)
            case 'NMS':
                pdScoresC = pdScoresHC['mean.2']

            # -WD (Without Disability -sans handicap)
            case 'WD':
                pdScoresC = pdScoresHC['mean.3']

    elif (gH == 'S' or gH == 'SA' or gH == 'SP'):

      pdScoresH = pdScoresHC['mean.2']
      match gC: # groupe de controle: -N, -NMS, -WD (-Neutre, -Malentendants et/ou Sourd, -non-handicap)

            # -N (Neutre)
            case 'N':
                pdScoresC = pdScoresHC['mean']

            # -NSM (Ni Sourds-Ni Malentendants (personnes entendantes)
            case 'NMS':
                pdScoresC = pdScoresHC['mean.1']

            # -WD (Without Disability -sans handicap)
            case 'WD':
                pdScoresC = pdScoresHC['mean.3']

    return pdScoresH,pdScoresC

# Définition de la fonction d'extraction des scores de MLM-ELECTRA
def extractScoresMLM(filePath,gH,gC):

    # parcourir le fichier .csv
    pdScores = pd.read_csv(filePath,sep=";", skipinitialspace=True)
    pdScoresHC = pdScores[2:]

    # Extraire les scores des groupes de Handicap (M,MS,S,SA,SP), de Controle (N,NMS) ou de non-handicap (WD)
    pdScoresH = []
    pdScoresC = []

    if (gH == 'M' or gH == 'MS' or gH == 'S' or gH == 'SA' or gH == 'SP'):

       match gH: # groupe de handicap

            # Malentendant
            case 'M':
                pdScoresH = pdScoresHC[('mean', 'ScoreMean', 'M')]

            # Malentendants / Sourd
            case 'MS':
                pdScoresH = pdScoresHC[('mean', 'ScoreMean', 'MS')]

            # Sourd

            case 'S':
                pdScoresH = pdScoresHC[('mean', 'ScoreMean', 'S')]

            # Sourd-Aveugle
            case 'SA':
                pdScoresH = pdScoresHC[('mean', 'ScoreMean', 'SA')]

            # Sourd-Plus
            case 'SP':
                pdScoresH = pdScoresHC[('mean', 'ScoreMean', 'SP')]

       match gC: # groupe de controle: -N, -NMS, -WD (-Neutre, -Malentendants et/ou Sourd, -non-handicap)

            # -N (Neutre)
            case 'N':
                pdScoresC = pdScoresHC[('mean', 'ScoreMean', 'N')]

            # -NSM (Ni Sourds-Ni Malentendants (personnes entendantes)
            case 'NMS':
                pdScoresC = pdScoresHC[('mean', 'ScoreMean', 'NMS')]

            # -WD (Without Disability -sans handicap)
            case 'WD':
                pdScoresC = pdScoresHC[('mean', 'ScoreMean', 'WD')]

    return pdScoresH,pdScoresC

# Définition des fonctions de calcul de la statistique t (test-t de Student)
def testDeStudent(filePath,gH,gC,alpha,model):

    # Extraire les scores des groupes de Handicap (M,MS,S,SA,SP), de Controle (N,NMS) ou de non-handicap (WD)
    if model == 'EM':
        pdScoresH,pdScoresC = extractScoresEC(filePath,gH,gC)
    else
        pdScoresH,pdScoresC = extractScoresMLM(filePath,gH,gC)

    # Calcul de la statistique-t de Student
    tStat,pValue,hNull = test_t(alpha,pdScoresH.values,pdScoresC.values)

    return tStat,pValue,hNull

# calcul de la statistique t-test:
def test_t(alpha,scoresGrH,scoresGrC):

    t_stat, p_value = stats.ttest_ind(scoresGrH,scoresGrC)

    # Interpret the results:
    print(p_value)
    if p_value < alpha:
       print("Rejetez l’hypothèse nulle ; il existe une différence significative entre les deux groupes.")
       hypot_null = "faux"
    else:
       print("Ne pas rejeter l’hypothèse nulle ; il n'y a pas de différence significative entre les deux groupes.")
       hypot_null = "vrai"

    return t_stat,p_value,hypot_null

# Calcul de la statistique -t (test t de Student) pour tous les groupes

# Parcourir la liste des fichiers -.csv

# Choisir le modele a tester
#modele = "MLM-ELECTRA"
modele = "EmotionClassifier"
scores_path = ""
test_t_path = ""

if (modele == "MLM-ELECTRA") :
    scores_path  = "" # scores_path_MlmElectra
    test_t_path  = "" # test_t_path_MlmElectra

else: # EmotionClassifier
    scores_path  = scores_path_EmotionClassifier
    test_t_path  = test_t_path_EmotionClassifier

# lecture des fichiers scores .csv
# by - Connector+Mask+Label
file_paths_results = list(Path(scores_path).glob("*.csv"))

# Création d'un objet DataFrame
pdTestT = pd.DataFrame(columns = ['groups','t_stat','p_value', 'Hypothese_Null'])
pdTestT_groups = []
pdTestT_stat = []
pdTestT_pValue =[]
pdTestT_hypoNul = []

for file_result in file_paths_results:

  # extraire le nom du fichier sans l'extention
  fileName,ext = file_result.name.split(sep=".")

  # Extraite les codes des deux sous-groupes a traiter
  grHC = ""
  sgr = fileName[0:7]
  mgr = fileName[0:6]
  print("sgr = ",sgr)
  if (mgr != "metric"):
    sgHC,sep = sgr.split("-")
    sgH,sgC  = sgHC.split("_")

    print("H,C,sep = ",sgH,sgC,sep)
    # calcul de la statistique t
    alpha = 0.05
    t_stat, p_value, hypoNul = testDeStudent(file_result,sgH,sgC,alpha)

    # Transfert des résultats intermédiaires dans le DataFrame- pdTestT
    grHC =  sgH + "_" + sgC
    pdTestT_groups.append(grHC)
    pdTestT_stat.append(t_stat)
    pdTestT_pValue.append(p_value)
    pdTestT_hypoNul.append(hypoNul)

# Transfert des résultats dans le DataFrame- pdTestT
pdTestT['groups'] = pdTestT_groups.values
pdTestT['t_stat'] = pdTestT_stat.values
pdTestT['p_value'] = pdTestT_pValue.values
pdTestT['Hypothese_Null'] = pdTestT_hypoNul.values

# Transfert des résultats dans un fichier -.csv
outputFileNameCsv   = "test_t_" + str(alpha) + "_" + modele + ".csv"
pdTestT.to_csv(test_t_path  + outputFileNameCsv, sep=";", index=False)

#pdTestT.to_csv(test_t_path  + "test_t_"+ sgH + "_" + sgC + "_" + str(alpha) + "_modele_"+".csv", sep=";", index=False)

# Définition de la fonction de test de normalité (Shapiro-Wilk) des scores d'EmotionClassifier / MLM-ELECTRA

def shapiroTestNorm(filePath,gH,gC,alpha):

    # Extraire les scores des groupes de Handicap (M,MS,S,SA,SP), de Controle (N,NMS) ou de non-handicap (WD)
    pdScoresH,pdScoresC = extractScores(filePath,gH,gC)

    # Effectuer le test de Shapiro-Wilk
    shapiroH,pValueH = shapiro(pdScoresH)
    shapiroC,pValueC = shapiro(pdScoresC)

    # Interprétation des résultats
    hypoNormH = ""
    hypoNormC = ""
    # Le groupe de handicap
    if pValueH > alpha:
       print("Les données suivent une distribution normale (on ne rejette pas H0)")
       hypoNormH = "vrai"
    else:
       print("Les données ne suivent pas une distribution normale (on rejette H0)")
       hypoNormH = "faux"

    # Le groupe de contrôle
    if pValueC > alpha:
       print("Les données suivent une distribution normale (on ne rejette pas H0)")
       hypoNormC = "vrai"
    else:
       print("Les données ne suivent pas une distribution normale (on rejette H0)")
       hypoNormC = "faux"

    return shapiroH,pValueH,hypoNormH,shapiroC,pValueC,hypoNormC

# Test de normalité des scores de tous les groupes d'EmotionClassifier / MLM-ELECTRA

# Choisir le modele a tester
#modele = "MLM-ELECTRA"
modele = "EmotionClassifier"
scores_path = ""
test_t_path = ""

if (modele == "MLM-ELECTRA") :
    scores_path     = scores_path_MlmElectra
    norm_test_path  = norm_test_path_MlmElectra

else: # EmotionClassifier
    scores_path  = "" # scores_path_EmotionClassifier
    norm_test_path  = "" # norm_test_path_EmotionClassifier

# Charger les données depuis le fichier CSV
# by - Connector+Mask+Label
by = "ConnectorMaskLabel"
file_paths = list(Path(scores_path).glob("*.csv"))

# Création d'un objet DataFrame
pdTestN = pd.DataFrame(columns = ['groups','normH_stat','p_valueH', 'distib_NormH','normC_stat','p_valueC', 'distib_NormC'])
pdTestN_groups = []

# groupe de handicap
pdTestN_statH = []
pdTestN_pValueH =[]
pdTestN_dNormH = []

# groupe de controle
pdTestN_statC = []
pdTestN_pValueC =[]
pdTestN_dNormC = []

for file_result in file_paths:

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # Extraite les codes des deux sous-groupes a traiter
    grHC = ""
    sgr = fileName[0:7]
    mgr = fileName[0:6]
    print("sgr = ",sgr)
    if (mgr != "metric"):
       sgHC,sep = sgr.split("-")
       sgH,sgC  = sgHC.split("_")
       print("H,C,sep = ",sgH,sgC,sep)

    # Calcul du test de Shapiro
    alpha = 0.05
    shapH,pValH,hNormH,shapC,pValC,hNormC = shapiroTestNorm(file_result,sgH,sgC,alpha)

    # Transfert des résultats intermédiaires dans le DataFrame- pdTestT
    pdTestN_groups.append(sgHC)

    # groupe de handicap
    pdTestN_statH.append(shapH)
    pdTestN_pValueH.append(pValH)
    pdTestN_dNormH.append(hNormH)

    # groupe de contrôle
    pdTestN_statC.append(shapC)
    pdTestN_pValueC.append(pValC)
    pdTestN_dNormC.append(hNormC)

# Transfert des résultats dans le DataFrame- pdTestT
pdTestN['groups'] = pdTestN_groups

# groupe de handicap
pdTestN['normH_stat'] = pdTestN_statH
pdTestN['p_valueH'] = pdTestN_pValueH
pdTestN['distib_NormH'] = pdTestN_dNormH

# groupe de contrôle
pdTestN['normC_stat'] = pdTestN_statC
pdTestN['p_valueC'] = pdTestN_pValueC
pdTestN['distib_NormC'] = pdTestN_dNormC

# Transfert des résultats dans un fichier -.csv
outputFileNameCsv   = "Norm_test_" + str(alpha) + "_by_" + by + "_"+ modele + ".csv"
pdTestN.to_csv(norm_test_path  + outputFileNameCsv, sep=";", index=False)

#pdTestN.to_csv(norm_test_path  + "test_t_"+ sgH + "_" + sgC + "_" + str(alpha) + "_modele_"+".csv", sep=";", index=False)