# -*- coding: utf-8 -*-
"""PredictionEmotionsElectraClassifier_01Juin2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwTxhzbsInccBaZNkJoFJk5zZQiF69sm
"""

# Prédiction des émotions du clasificateur des émotions - EmotionClassifier
# Dernière modification: 14 Janvier 2025

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

#scoresElectraGenerator_path = '/content/drive/MyDrive/scoresElectraGenerator/'
scoresElectraGenerator_path = '/content/drive/MyDrive/ToDo/'
scoresEmotionClassifier_path = '/content/drive/MyDrive/scoresEmotionClassifier/'

import pandas as pd
from tqdm.auto import tqdm
tqdm.pandas()
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from pathlib import Path
#import torch

!pip install torchmetrics
!pip install pytorch_lightning

print("Preparing Electra Classifier...")
from electra_classifier import *

best_model_path = "/content/drive/MyDrive/checkpoints/epoch=86-step=6318-val_loss=0.01.ckpt"
emotion_categories = ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring',
       'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval',
       'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief',
       'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization',
       'relief', 'remorse', 'sadness', 'surprise', 'neutral']

MODEL_NAME = "google/electra-base-discriminator"

# Convertir le modèle formé en un modèle optimisé -CUDA-
#device = torch.device("cuda")

tokenizer = ElectraTokenizer.from_pretrained(MODEL_NAME)

trained_model = EmotionClassifier.load_from_checkpoint(
    # trainer.checkpoint_callback.best_model_path,
    best_model_path,
    #map_location= device,
    n_classes=len(emotion_categories)
)

# converti en -CUDA-
#trained_model.to(device)

# cette fonction predit une seule étiquette parmi les 28
def predict_emotion_and_probability(text):
    encoding = tokenizer(
          text,
          max_length=64,
          truncation=True,
          padding="max_length",
          add_special_tokens=True,
          return_token_type_ids=False,
          return_attention_mask=True,
          return_tensors="pt"
      )
    outputs = trained_model(**encoding)
    probabilities = list(torch.softmax(outputs, dim=-1).detach().numpy().flatten())
    emotion_idx = torch.argmax(outputs, dim=-1).item()
    predicted_emotion = emotion_categories[emotion_idx]

    emotion_categories_list = list(emotion_categories)
    probabilities, emotion_categories_list = zip(*sorted(zip(probabilities, emotion_categories_list)))
    probabilities = probabilities[::-1]
    emotion_categories_list = emotion_categories_list[::-1]
    emotion_probability = round(100*probabilities[0], 2)#:.2f

    return predicted_emotion, emotion_probability

print("Electra Classifier is ready!")

# Définition d'une fonction qui retourne les scores du modele - EmotionElectraClassifier- appliqué sur les prompts
# (remplis avec les tokens prédits par le modele de langue -ElectraGenerator-) dans un objet Dataframe

def calculScoreElectra(aSequence):

    # Parcourir les sequences et calculer les scores des émotions
    labelSequence = []
    probabilitySequence = []
    scoresSequence = []

    for i in range(aSequence.size):
        prompt = aSequence[i]
        labelE,scoresE = predict_emotion_and_probability(prompt)
        labelSequence.append(labelE)
        probabilitySequence.append(scoresE)

    scoresSequence = pd.DataFrame(columns = ['label', 'probability'])
    scoresSequence['label'] = labelSequence
    scoresSequence['probability'] = probabilitySequence

    return scoresSequence


# Définition d'une fonction qui retourne les sequences prédites dans un objet Dataframe

def sequencesPredictT(filePath):

    print("filePath = ", filePath)

    sequencesPd = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # extraire les champs déjà existants dans le Dataframe précédent
    tPrompts = sequencesPd["prompts"]
    tCategories = sequencesPd["categorie"]
    tGroupes = sequencesPd["groupe"]
    tSousGroupes = sequencesPd["sousGroupe"]
    tSpaceHolders = sequencesPd["spaceHolder"]
    tConnecteurs = sequencesPd["connector"]
    tReferences = sequencesPd["reference"]

    tMask1 = sequencesPd["mask1"]
    tMask2 = sequencesPd["mask2"]
    tMask3 = sequencesPd["mask3"]

    tSequence1 = sequencesPd["sequence1"]
    tSequence2 = sequencesPd["sequence2"]
    tSequence3 = sequencesPd["sequence3"]

    scoresSequence = []

    # Créer un Dataframe pour recuperer les émotions (labels et probabilités) : 'spaceHolder',

    scoresElectra = pd.DataFrame(columns = ['prompts', 'categorie', 'groupe', 'sousGroupe', 'spaceHolder', 'connector' , 'reference' , 'mask1', 'sequence1', 'label1', 'probability1', 'mask2','sequence2', 'label2', 'probability2', 'mask3', 'sequence3', 'label3', 'probability3'])

    # récuperer les champs déjà existants
    scoresElectra['prompts']     = tPrompts
    scoresElectra['categorie']   = tCategories
    scoresElectra['groupe']      = tGroupes
    scoresElectra['sousGroupe']  = tSousGroupes
    scoresElectra['spaceHolder']  = tSpaceHolders
    scoresElectra['connector']  = tConnecteurs
    scoresElectra['reference']   = tReferences

    scoresElectra['mask1']   = tMask1
    scoresElectra['mask2']   = tMask2
    scoresElectra['mask3']   = tMask3

    scoresElectra['sequence1']   = tSequence1
    scoresElectra['sequence2']   = tSequence2
    scoresElectra['sequence3']   = tSequence3

    # calcul des scores de prédiction des étiquettes d'émotion
    cSq1 = calculScoreElectra(tSequence1)
    scoresElectra['label1'] = pd.Series(cSq1['label'])
    scoresElectra['probability1'] = pd.Series(cSq1['probability'])

    cSq2 = calculScoreElectra(tSequence2)
    scoresElectra['label2'] = pd.Series(cSq2['label'])
    scoresElectra['probability2'] = pd.Series(cSq2['probability'])

    cSq3 = calculScoreElectra(tSequence3)
    scoresElectra['label3'] = pd.Series(cSq2['label'])
    scoresElectra['probability3'] = pd.Series(cSq3['probability'])

    return scoresElectra

# Calcul des scores des émotions du modele -EmotionElectraClassifier- appliqué sur
# les prompts remplis et enregistrement des résultats dans des fichiers -.csv et -.xslx

# Parcourir la liste des fichiers -.csv (les prédictions du -MlmElectra-)
file_paths_results = list(Path(scoresElectraGenerator_path).glob("*.csv"))
dfResultsT = []

for file_result in file_paths_results:

    print("file_result = ", file_result)
    dfResultsT = sequencesPredictT(file_result)

    # extraire le nom du fichier sans l'extention
    fileName,ext = file_result.name.split(sep=".")

    # concatener (le nom du modele Electra choisi + la tâche + l'extention -.csv ou -.excel)
    # electraModelName = "lMlmElectra_"

    outputFileNameCsv = "scoresEmotionClassifier_" + fileName + ".csv"
    #outputFileNameExcel = "scoresEmotionElectraClassifier_" + fileName + ".xlsx"

    # Transfert des résultats dans un fichier csv/excel.
    dfResultsT.to_csv(scoresEmotionClassifier_path + outputFileNameCsv, sep=";", index=False)
    #dfResultsT.to_excel(scoresEmotionElectraClassifier_path + outputFileNameExcel, index=False)



