# -*- coding: utf-8 -*-
"""SondageElectraLargeGenerateur_29Mai2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hbBZSlTxBX692M1QXHwTuQ5RbARR3sub
"""

# Programme de prédiction des jetons masqués de tous les prompts crées
# Le modele de langue choisi : le génerateur d'Electra-Large

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

# définir les chemins d'entrée / sortie des données
data_path = '/content/drive/MyDrive/GeneratedPrompts/'
predictMlm_path = '/content/drive/MyDrive/scoresElectraGenerator/'
#filesFiltred_path = '/content/drive/MyDrive/filtredFiles/'

import torch
import os
from pathlib import Path
import pandas as pd
import numpy as np
import array as ar
from transformers import pipeline
import json
from scipy import stats

print(torch.cuda.is_available())
print(torch.cuda.device_count())
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device = torch.device('cuda')
print(device)

# Création du pipeline de prédiction
fill_mask = pipeline(
    "fill-mask",
    model="google/electra-large-generator",
    device= device,
    tokenizer="google/electra-large-generator",
    #model="google/electra-base-generator",
    #tokenizer="google/electra-base-generator",
    #model="google/electra-small-generator",
    #tokenizer="google/electra-small-generator",
    top_k=3
)
modelName = fill_mask.model.name_or_path
print(fill_mask.device)

if modelName == "google/electra-small-generator":
     electraModelName = "SmallGeneratorElectra_"
elif modelName == "google/electra-base-generator":
     electraModelName = "BaseGeneratorElectra_"
elif modelName == "google/electra-large-generator":
     electraModelName = "LargeGeneratorElectra_"

# Définition d'une fonction qui retourne les préditions du MLM choisi (ElctraGenerator: Small / Base / Large) dans un objet Dataframe

def promptsFillMask(filePath):

    print(file_path.name)
    promptsFillMask = pd.read_csv(filePath,sep=";", skipinitialspace=True)

    # Extraire les 3 premiers masques avec leurs scores et sequences dans un DataFrame

    aPrompts = promptsFillMask["prompts"]
    aMasks1 = []
    aMasks2= []
    aMasks3 = []

    aScore1 = ar.array('f')
    aScore2 = ar.array('f')
    aScore3 = ar.array('f')

    aSequence1 = []
    aSequence2 = []
    aSequence3 = []

    # Parcourir les prompts du fichier csv
    for i in range(aPrompts.size):
        prompt = aPrompts[i]
        fillMasque = fill_mask(prompt)
        #jsonMasque = json.dumps(fillMasque, indent=4)

        aMasks1.append(fillMasque[0]["token_str"])
        aScore1.append(fillMasque[0]["score"])
        aSequence1.append(fillMasque[0]["sequence"])

        aMasks2.append(fillMasque[1]["token_str"])
        aScore2.append(fillMasque[1]["score"])
        aSequence2.append(fillMasque[1]["sequence"])

        aMasks3.append(fillMasque[2]["token_str"])
        aScore3.append(fillMasque[2]["score"])
        aSequence3.append(fillMasque[2]["sequence"])

    # On récupere les 3 premiers tokens prédits, leurs scores et leurs sequences correspondants

    promptsFillMask['mask1'] = pd.Series(aMasks1)
    promptsFillMask['score1'] = pd.Series(aScore1)
    promptsFillMask['sequence1'] = pd.Series(aSequence1)

    promptsFillMask['mask2'] = pd.Series(aMasks2)
    promptsFillMask['score2'] = pd.Series(aScore2)
    promptsFillMask['sequence2'] = pd.Series(aSequence2)

    promptsFillMask['mask3'] = pd.Series(aMasks3)
    promptsFillMask['score3'] = pd.Series(aScore3)
    promptsFillMask['sequence3'] = pd.Series(aSequence3)

    return promptsFillMask

# Prédiction des tokens masqués de tous les prompts (les fichiers -.csv) et enregistrement des résultats du MLM dans des fichiers -.csv et -.xslx

# Parcourir la liste des fichiers -.csv (les prompts)
file_paths = list(Path(data_path).glob("*.csv"))
dfPrompts = []
for file_path in file_paths:

  dfPrompts = promptsFillMask(file_path)
  print(dfPrompts.head)

  # extraire le nom du fichier sans l'extention
  fileName,ext = file_path.name.split(sep=".")

  # concatener (le nom du modele Electra choisi + l'extention -.csv ou -.excel)
  outputFileNameCsv = "scoresOf"+electraModelName+fileName+".csv"
  #outputFileNameExcel = "scoresOf"+electraModelName+fileName+".xlsx"

  # Transfert des résultats dans un fichier -.csv/-.excel.
  dfPrompts.to_csv(predictMlm_path + outputFileNameCsv, sep=";", index=False)
  #dfPrompts.to_excel(predictMlm_path + outputFileNameExcel, index=False)

# Filtrer les prédictions du -MlmElectra selon la rubriqye -Ignore == non

def filterPredictMlm(fileToFilter):
    # Lecture du fichier -.csv a filter (les prédictions)
    dfPredict = pd.read_csv(fileToFilter,sep=";", skipinitialspace=True)
    dfFiltredPredict = dfPredict.loc[dfPredict['ignore'] == 'non']

    return dfFiltredPredict

# Parcourir la liste des fichiers -.csv (contenant les predictions)
filesToFilter_paths = list(Path(predictMlm_path).glob("*.csv"))
dfFiltred = []

for fileToFilter_path in filesToFilter_paths:

   dfFiltred = filterPredictMlm(fileToFilter_path)
   print(dfFiltred)

   # extraire le nom du fichier sans l'extention
   fileName,ext = fileToFilter_path.name.split(sep=".")

   # concatener (le nom du modele Electra choisi + l'extention -.csv ou -.excel)
   outputFileNameCsv = "scoresOf"+electraModelName+fileName+".csv"
   #outputFileNameExcel = "scoresOf"+electraModelName+fileName+".xlsx"

   # Transfert des résultats dans un fichier -.csv/-.excel.
   dfFiltred.to_csv(filesFiltred_path + outputFileNameCsv, sep=";", index=False)
   #dfFiltred.to_excel(filesFiltred_path + outputFileNameExcel, index=False)