# -*- coding: utf-8 -*-
"""WilcoxonTestMlmElectra_01Juin2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfj94MsyqwsFXc-yX0rVX-OEXA7cQEHF
"""

# Le programme des tests statistiques non paramétrique de Wilcoxon Test
# Analyse des scores de prédiction (les probabilités) de MlmElectra (le générateur)
# Dernière modification: 28 Octobre 2025

# Monter google drive

from google.colab import drive
drive.mount('/content/drive')

#metrics_ScoreSens_path = '/content/drive/MyDrive/ToDo/'
#metrics_ScoreSens_path = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsElectraGenerator/ScoreSensElectraGenerator/'
#wilcoxonTest_path = '/content/drive/MyDrive/metrics/wilcoxonTestElectraGenerator/'

#metrics_ScoreSensCateg_path = '/content/drive/MyDrive/ToDo/'
metrics_ScoreSensCateg_path  = '/content/drive/MyDrive/metrics/Prabhakaran2019/metricsElectraGenerator/ScoreSensCategElectraGenerator/'

wilcoxonTestCateg_path = '/content/drive/MyDrive/metrics/wilcoxonTestCateg_ElectraGenerator/'
#wilcoxonTestCateg_path = '/content/drive/MyDrive/ToDoSave/'

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from pathlib import Path
import torch
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html
from scipy.stats import wilcoxon

# import seaborn as sns
# from tqdm.auto import tqdm
# tqdm.pandas()

# emotion_categories = ['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral']
# Les 18 verbes connecteurs (dont 14 de Hassan Saad)
# ['job', 'to advise', 'to be', 'to develop', 'to do', 'to feel', 'to guide', 'to have', 'to innovate', 'to instruct', 'to lead', 'to manage', 'to need', 'to perceive', 'to produce', 'to supervise', 'to teache', 'to work']

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# torch.device("cuda:0")
#device = torch.device("cuda")

# Définition de la fonction de calcul du test statistique (Wilcoxon)

def wilcoxonTest(grH,grC):

  # Perform the Wilcoxon Signed-Rank test for two paired groups
  # (grH: diability group, grC: control group)

  #print("Wilcoxon Signed-Rank Test Statistic")

  #print("Wilcoxon Signed-Rank Test Statistic : grH: ", grH)
  print("TAILLE grH = ", grH.size, "TAILLE grC = ", grC.size)

  statistic, p_value = wilcoxon(grH, grC, alternative='two-sided')

  print(f"Wilcoxon Signed-Rank Test Statistic: {statistic}")
  print(f"P-value: {p_value}")

  # Interpret the results
  alpha = 0.05
  res = ""

  # The null hypothesis : There is no significant difference between the two paired groupes
  # L'hypothèse nulle : Il n'y a pas de différence significative entre les deux groupes appariés

  if p_value < alpha:
     res = "RNH"
     print("Reject the null hypothesis: There is a significant difference between the two paired groupes: (" + H + "," + C + ")")
  else:
     res = "ANH"
     print("Fail to reject the null hypothesis: There is no significant difference between the two paired groupes: (" + H + "," + C + ")")

  return statistic,p_value,res

# Définition de la fonction de calcul du test Wilcoxon par connecteur
# pour chaque paire de groupes (groupe de handicap, groupe de contôle)

def wilcoxonTestByParedGroup(pdMetricFile,c_cm_m,connectorVerbs,H,C):

    scores_grHC = pd.DataFrame()

    print("cCmM = " , c_cm_m)
    # Création des DataFrames
    pdTestWilcoxon = pd.DataFrame(columns = ['Paired group','statistic','p_value','Test Result'])
    if (c_cm_m == 'Mask') : scores_grHC = pd.DataFrame(columns = ['mask','meanH','meanC'])
    else: scores_grHC = pd.DataFrame(columns = ['connector','meanH','meanC'])

    # Extraire les scores pour chaque paire de groupes (grH,grC) :
    # (M:Malentendant,N:Neutre),(S:Sourd,N:Neutre),(MS:Malentendant et/ou Sourd,N:Neutre),(SA:Sourd-Aveugle,N:Neutre),(SP:Sourd-Plus,N:Neutre)
    # (M:Malentendant,NMS:Entendant),(S:Sourd,NMS:Entendant),(MS:Malentendant et/ou Sourd,NMS:Entendant),(SA:Sourd-Aveugle,NMS:Entendant),(SP:Sourd-Plus,NMS:Entendant)
    # (M:Malentendant,WD:Without Disability),(S:Sourd,WD:Without Disability),(MS:Malentendant et/ou Sourd,WD:Without Disability),(SA:Sourd-Aveugle,WD:Without Disability),(SP:Sourd-Plus,WD:Without Disability)


    # les groupes de handicap (M,MS)
    if (H == 'M' or H == 'MS'):
       scores_grHC['meanH'] = pdMetricFile['mean']

       # les groupes de contrôle (N,NMS,WD)
       match C:
           # les scores du groupe de contrôle (N)
           case 'N': # Neutre
                 scores_grHC['meanC'] = pdMetricFile['mean.1']

           # les scores du groupe de contrôle (NMS)
           case 'NMS': # Entendant
                 scores_grHC['meanC'] = pdMetricFile['mean.2']
           # les scores du groupe de contrôle (WD)
           case 'WD': # Without Disability
                 scores_grHC['meanC'] = pdMetricFile['mean.3']

    # les groupes de handicap (S,SA,SP)
    elif (H == 'S' or H == 'SA' or H == 'SP'):
         scores_grHC['meanH'] = pdMetricFile['mean.2']

         # les groupes de contrôle (N,NMS,WD)
         match C:
           # les scores du groupe de contrôle (N)
           case 'N': # Neutre
                 scores_grHC['meanC'] = pdMetricFile['mean']

           # les scores du groupe de contrôle (NMS)
           case 'NMS': # Entendant
                 scores_grHC['meanC']  = pdMetricFile['mean.1']

           # les scores du groupe de contrôle (WD)
           case 'WD': # Without Disability
                 scores_grHC['meanC']  = pdMetricFile['mean.3']

    # Test de Wilcoxon pour chaque paire de groupe (grH,grC)
    #pdTestWilcoxon = pd.Series()
    pGr = [] # la liste des paires de groupes (grH,grC)
    zStat = [] # la liste de la statistic de chaque paires de groupes (grH,grC)
    pValue = [] # la liste de p_value de chaque paires de groupes (grH,grC)
    resW = [] # la liste du reultat du test de chaque paires de groupes (grH,grC)

    # Calcul du test de Wilcoxon par connecteur pour chaque paire de groupe (grH,grC)

    #print("data grHC = ", scores_grHC, "TAILLE grHC = ",len(scores_grHC))

    if (c_cm_m == 'ConnectorMask'): # test Wilcoxon par connecteur (ou connecteur+mask)

       # Transfert des connecteurs
       scores_grHC['connector'] = pdMetricFile['connector']

       for vc in connectorVerbs:
           # Filtrer par verbe conneteur si la taille ­superieur a 18
           scores_grHC_VC = pd.DataFrame()
           scores_grHC_VC = scores_grHC.loc[(scores_grHC['connector'] == vc)]

           print("data grH par connecteur_mask = ", scores_grHC_VC)

           # test de Wilcoxon
           statistic,p_value,res = wilcoxonTest(scores_grHC_VC['meanH'].values,scores_grHC_VC['meanC'].values)
           pGr.append(H+"&"+C)
           zStat.append(statistic)
           pValue.append(p_value)
           resW.append(res)

       # transfert des resultats dans le DataFrames
       pdTestWilcoxon['Connector'] = connectorVerbs
       pdTestWilcoxon['Paired group'] = pGr
       pdTestWilcoxon['statistic'] = zStat
       pdTestWilcoxon['p_value'] = pValue
       pdTestWilcoxon['Test Result'] = resW

    else : # test Wilcoxon pour tous les connecteurs ou (tous les masks)

         # test de Wilcoxon
         statistic,p_value,res = wilcoxonTest(scores_grHC['meanH'].values,scores_grHC['meanC'].values)

         # transfert des resultats dans le DataFrames

         #pdTestWilcoxon = pdTestWilcoxon.add({'Paired group':H+"&"+C, 'statistic':statistic, 'p_value':p_value, 'Test Result':res})
         pdTestWilcoxon.loc[len(pdTestWilcoxon)] = [np.nan,np.nan,np.nan,np.nan]

         pdTestWilcoxon.iat[0,0] = H+"&"+C
         pdTestWilcoxon.iat[0,1] = statistic
         pdTestWilcoxon.iat[0,2] = p_value
         pdTestWilcoxon.iat[0,3] = res

    return pdTestWilcoxon

# Transfert des résultats du test de Wilcoxon (MLM-Electra: le générateur)
# dans des fichiers .csv

connectorVerbs = ['job', 'to advise', 'to be', 'to develop', 'to do', 'to feel', 'to guide', 'to have', 'to innovate', 'to instruct', 'to lead', 'to manage', 'to need', 'to perceive', 'to produce', 'to supervise', 'to teache', 'to work']

# Parcourir la liste des fichiers -.csv du repertoire (ScoreSens Metric)
file_paths_metrics = list(Path(metrics_ScoreSens_path).glob("*.csv"))

# Traiter le fichier .csv (ScoreSens metric)
for file_metric in file_paths_metrics:


   # Lecture du fichier .csv
   pdMetricFile = pd.read_csv(file_metric,sep=";", skipinitialspace=True)

   # Extraire le nom du fichier sans l'extention
   fileName,ext = file_metric.name.split(sep=".")
   nameCsv,name2  = fileName.split(sep="All")

   # Extraire les codes de la paire de groupes a traiter
   HC,s = nameCsv.split("-by_")
   sgr = HC[0:6]
   if (sgr != 'metric') :
      H,C = HC.split("_")
      print("fileName= "+file_metric.name, "H= "+H,"C= "+C, "c_cm_m= "+s)

      # Ignorer les 2 premieres lignes (-NaN-)
      pdMetricFile = pdMetricFile[2:]

      # Convertir les colonnes en numerique
      pdMetricFile = pdMetricFile.astype({'mean': 'float', 'mean.1': 'float', 'mean.2': 'float', 'mean.3': 'float'})

      # Vérifier
      #pdSize = pdMetricFile['connector'].values.size
      #print("taille pdZise = ", pdSize)

      # Test de Wilcoxon
      pdtestW = wilcoxonTestByParedGroup(pdMetricFile,s,connectorVerbs,H,C)

      #print("Retour = ", pdtestW)

      # Transfert des résultats dans un fichier -.csv
      outputFileNameCsv = nameCsv + "-WilcoxonTest" + "_MlmElectra" + ".csv"
      pdtestW.to_csv(wilcoxonTest_path  + outputFileNameCsv, sep=";", index=False)

# FIN DU PROGRAMME - TEST DE WILCOXON.

# Définition de la fonction de transfert des resultats de test Wilcoxon dans le DataFrames:
# par Categorie de handicap (R / NR).

def wilcoxonTestCategSave(pdTestWCateg,categ,grPair,statisticCateg,pValueCateg,resCateg):

   print("categ= " + categ, "grPair= " + grPair, "statisticCateg= ", statisticCateg, "pValueCateg= ",pValueCateg, "resCateg= " + resCateg)

   i = len(pdTestWCateg)
   pdTestWCateg.loc[len(pdTestWCateg)] = [np.nan,np.nan,np.nan,np.nan,np.nan]
   pdTestWCateg.iat[i,0] = categ
   pdTestWCateg.iat[i,1] = grPair
   pdTestWCateg.iat[i,2] = statisticCateg
   pdTestWCateg.iat[i,3] = pValueCateg
   pdTestWCateg.iat[i,4] = resCateg

   print("wilcoxonTestCategSave: ", pdTestWCateg)
   return pdTestWCateg

# Définition de la fonction de calcul du test statistique de Wilcoxon (MLM-Electra: le générateur):
# par Categorie de handicap (R / NR).

def wilcoxonTestCateg(grH,grC):

  # Perform the Wilcoxon Signed-Rank test for two paired groups
  # (grH: diability group, grC: control group)

  #print("Wilcoxon Signed-Rank Test Statistic")

  #print("Wilcoxon Signed-Rank Test Statistic : grH: ", grH)
  print("TAILLE grH = ", grH.size, "TAILLE grC = ", grC.size)
  print("Wilcoxon Test (groupe de Handicap):", grH)
  print("Wilcoxon Test (groupe de Contrôle):", grC)

  statistic, p_value = wilcoxon(grH, grC, alternative='two-sided')

      #print(f"Wilcoxon Signed-Rank Test Statistic: {statistic}")
      #print(f"P-value: {p_value}")

  # Interpret the results
  alpha = 0.05
  res = ""

  # The null hypothesis : There is no significant difference between the two paired groupes
  # L'hypothèse nulle : Il n'y a pas de différence significative entre les deux groupes appariés

  if p_value < alpha:
     res = "RNH"
        #print("Reject the null hypothesis: There is a significant difference between the two paired groupes:")
  else:
     res = "ANH"
         #print("Fail to reject the null hypothesis: There is no significant difference between the two paired groupes:")

  return statistic,p_value,res

# Définition de la fonction de calcul du test Wilcoxon par connecteur & par Categorie de
# handicap (R / NR) pour chaque paire de groupes (groupe de handicap, groupe de contôle)

def wilcoxonTestCategByParedGroup(pdMetricFile,nCCM,connectorVerbs,H,Cnms,Cn,Cwd):

    scoresCateg_grHC = pd.DataFrame()
    grPairCn   = ""
    grPairCnms = ""
    grPairCwd  = ""

    print("nCCM = " + nCCM, "H = " + H, "Cn = " + Cn, "Cnms = " + Cnms, "Cwd = " + Cwd)

    # Création des DataFrames
    pdTestWilcoxonCateg = pd.DataFrame(columns = ['categorie','Paired group','statistic','p_value','Test Result'])
    scoresCateg_grHC = pd.DataFrame(columns = ['categorie','connector','meanH','meanCn','meanCnms','meanCwd'])

    # nCCM = (CategConnectorMask / CategMask / ConnectorCateg / ConnectorMaskCateg /  MaskCateg)
    #if (nCCM == 'CategMask') : scoresCateg_grHC = pd.DataFrame(columns = ['categorie','mask','meanH','meanCn','meanCnms','meanCwd'])
    #else: scoresCateg_grHC = pd.DataFrame(columns = ['categorie','connector','meanH','meanCn','meanCnms','meanCwd'])


    # Extraire les scores pour chaque paire de groupes (grH,grC) :
    # (M:Malentendant,N:Neutre),(S:Sourd,N:Neutre),(MS:Malentendant et/ou Sourd,N:Neutre),(SA:Sourd-Aveugle,N:Neutre),(SP:Sourd-Plus,N:Neutre)
    # (M:Malentendant,NMS:Entendant),(S:Sourd,NMS:Entendant),(MS:Malentendant et/ou Sourd,NMS:Entendant),(SA:Sourd-Aveugle,NMS:Entendant),(SP:Sourd-Plus,NMS:Entendant)
    # (M:Malentendant,WD:Without Disability),(S:Sourd,WD:Without Disability),(MS:Malentendant et/ou Sourd,WD:Without Disability),(SA:Sourd-Aveugle,WD:Without Disability),(SP:Sourd-Plus,WD:Without Disability)

    # Transfert des categories (R / NR)
    scoresCateg_grHC['categorie'] = pdMetricFile['categorie']

    # les groupes de handicap (M,MS)
    if (H == 'M' or H == 'MS'):
       scoresCateg_grHC['meanH'] = pdMetricFile['mean']

    # les groupes de contrôle (N,NMS,WD)
       # Neutre (N)
       if (Cn == 'N'): scoresCateg_grHC['meanCn'] = pdMetricFile['mean.1']
       # Entendant (NMS)
       if (Cnms == 'NMS'): scoresCateg_grHC['meanCnms'] = pdMetricFile['mean.2']
       # Without Disability (WD)
       if (Cwd == 'WD'): scoresCateg_grHC['meanCwd'] = pdMetricFile['mean.3']

    # les groupes de handicap (S,SA,SP)
    elif (H == 'S' or H == 'SA' or H == 'SP'):
         scoresCateg_grHC['meanH'] = pdMetricFile['mean.2']

         # les groupes de contrôle (N,NMS,WD)
         # Neutre
         if (Cn == 'N'): scoresCateg_grHC['meanCn'] = pdMetricFile['mean']
         # Entendant
         if (Cnms == 'NMS'): scoresCateg_grHC['meanCnms']  = pdMetricFile['mean.1']
         # Without Disability
         if (Cwd == 'WD'): scoresCateg_grHC['meanCwd']  = pdMetricFile['mean.3']

    # Test de Wilcoxon pour chaque paire de groupe (grH,grC) / par categorie (R /NR)

    # Filtrage par categorie (R/NR)
      # groupe de handicap
    scoresR_grHC = pd.DataFrame()
    scoresR_grHC = scoresCateg_grHC.loc[(scoresCateg_grHC['categorie'] == 'R')]
    scoresNR_grHC = pd.DataFrame()
    scoresNR_grHC = scoresCateg_grHC.loc[(scoresCateg_grHC['categorie'] == 'NR')]

    #print("La paire de groupe = ", H + "&" + Cn)
    #print("data par connecteur/categorie R = ", scoresR_grHC)
    #print("data par connecteur/categorie NR = ", scoresNR_grHC)

    # Calcul -Wilcoxon Test- pour tous les connecteurs et pour chaque paire de groupe (grH,grC):
    if (nCCM == 'ConnectorCateg'):

       # test de Wilcoxon- par rapport au groupe de contrôle Neutre (N)
       statisticR,p_valueR,resR = wilcoxonTestCateg(scoresR_grHC['meanH'].values,scoresR_grHC['meanCn'].values)
       statisticNR,p_valueNR,resNR = wilcoxonTestCateg(scoresNR_grHC['meanH'].values,scoresR_grHC['meanCn'].values)

                          # transfert des resultats dans le DataFrames (groupe de contrôle Neutre: N)
       grPairCn = H+"&"+Cn
       pdTestWilcoxonCateg = wilcoxonTestCategSave(pdTestWilcoxonCateg,'R',grPairCn,statisticR,p_valueR,resR)
       pdTestWilcoxonCateg = wilcoxonTestCategSave(pdTestWilcoxonCateg,'NR',grPairCn,statisticNR,p_valueNR,resNR)

       # test de Wilcoxon- par rapport au groupe de contrôle Entendant (NMS)
       statisticR,p_valueR,resR = wilcoxonTestCateg(scoresR_grHC['meanH'].values,scoresR_grHC['meanCnms'].values)
       statisticNR,p_valueNR,resNR = wilcoxonTestCateg(scoresNR_grHC['meanH'].values,scoresR_grHC['meanCnms'].values)

                           # transfert des resultats dans le DataFrames (groupe de contrôle Entendant: NMS)
       grPairCnms = H+"&"+Cnms
       pdTestWilcoxonCateg = wilcoxonTestCategSave(pdTestWilcoxonCateg,'R',grPairCnms,statisticR,p_valueR,resR)
       pdTestWilcoxonCateg = wilcoxonTestCategSave(pdTestWilcoxonCateg,'NR',grPairCnms,statisticNR,p_valueNR,resNR)

       # test de Wilcoxon- par rapport au groupe de contrôle Without Disability (WD)
       statisticR,p_valueR,resR = wilcoxonTestCateg(scoresR_grHC['meanH'].values,scoresR_grHC['meanCwd'].values)
       statisticNR,p_valueNR,resNR = wilcoxonTestCateg(scoresNR_grHC['meanH'].values,scoresR_grHC['meanCwd'].values)

                           # transfert des resultats dans le DataFrames (groupe de contrôle  Without Disability: WD)
       grPairCwd = H+"&"+Cwd
       pdTestWilcoxonCateg = wilcoxonTestCategSave(pdTestWilcoxonCateg,'R',grPairCwd,statisticR,p_valueR,resR)
       pdTestWilcoxonCateg = wilcoxonTestCategSave(pdTestWilcoxonCateg,'NR',grPairCwd,statisticNR,p_valueNR,resNR)

    return pdTestWilcoxonCateg

# Transfert des résultats du test de Wilcoxon (MLM-Electra: le générateur)
# par Categorie de handicap (R / NR) dans des fichiers .csv

connectorVerbs = ['job', 'to advise', 'to be', 'to develop', 'to do', 'to feel', 'to guide', 'to have', 'to innovate', 'to instruct', 'to lead', 'to manage', 'to need', 'to perceive', 'to produce', 'to supervise', 'to teache', 'to work']

# Parcourir la liste des fichiers -.csv du repertoire (ScoreSens Metric)
file_paths_metrics = list(Path(metrics_ScoreSensCateg_path).glob("*.csv"))

# Traiter le fichier .csv (ScoreSens metric)
for file_metric in file_paths_metrics:

   # Lecture du fichier .csv
   pdMetricFile = pd.read_csv(file_metric,sep=";", skipinitialspace=True)

   # Extraire le nom du fichier sans l'extention
   fileName,ext = file_metric.name.split(sep=".")

   # Extraire les codes de la paire de groupes a traiter

   print("fileName= "+file_metric.name,"s= "+s,"nCCM = "+ nCCM, "H= "+H,"n1= "+c1,"n2= "+c2,"n3= "+c3)

   nameCsv,name2  = fileName.split(sep="All")
   sgr = nameCsv[0:6]

   if (sgr == 'metric') :
      nCsv,nCCM = nameCsv.split(sep="_") # nCCM = (CategConnectorMask / CategMask / ConnectorCateg / ConnectorMaskCateg /  MaskCateg)
      nm1,nm2 = name2.split(sep="-")
      s,H,c1,c2,c3 = nm1.split(sep="_")

      #print("fileName= "+file_metric.name,"s= "+s,"nCCM = "+ nCCM, "H= "+H,"n1= "+c1,"n2= "+c2,"n3= "+c3)

      # Ignorer les 2 premieres lignes (-NaN-)
      pdMetricFile = pdMetricFile[2:]

      # Convertir les colonnes en numerique
      pdMetricFile = pdMetricFile.astype({'mean': 'float', 'mean.1': 'float', 'mean.2': 'float', 'mean.3': 'float'})

      # Vérifier
      #pdSize = len(pdMetricFile)
      #print("taille pdZise = ", pdSize)

      # Test de Wilcoxon

      # (nCCM == 'CategConnectorMask' ou 'ConnectorMaskCateg'  / 'CategMask' ou 'MaskCateg' / 'ConnectorCateg')
      if (nCCM == 'ConnectorCateg'): # test Wilcoxon pour tous les connecteurs par categorie (nCCM == 'ConnectorCateg'):
         pdtestW = wilcoxonTestCategByParedGroup(pdMetricFile,nCCM,connectorVerbs,H,c1,c2,c3)

         #print("Retour = ", pdtestW)

         # Transfert des résultats dans un fichier -.csv
         outputFileNameCsv = H + "_" + nCCM + "-WilcoxonTestCateg" + "_MlmElectra" + ".csv"
         pdtestW.to_csv(wilcoxonTestCateg_path  + outputFileNameCsv, sep=";", index=False)

# FIN DU PROGRAMME - TEST DE WILCOXON - par Categorie de handicap (R / NR).